static class BattleRootHudAllocationReviewGate
{
    public static void Check(string root, GateResult result)
    {
        var battleRoot = ReviewGateEvidence.ReadSourceWithPartials(
            Path.Combine(root, "scripts", "BattleRoot.cs"));
        var process = ReviewGateSource.Read(root, "scripts", "BattleRoot.Process.cs");
        var minimap = ReviewGateSource.Read(root, "scripts", "battle-root", "BattleRoot.HudMinimap.cs");
        var alerts = ReviewGateSource.Read(root, "scripts", "BattleRoot.Alerts.cs");
        var sandbox = ReviewGateSource.Read(root, "scripts", "BattleRoot.Sandbox.cs");
        var hudState = ReviewGateSource.Read(root, "scripts", "ui", "hud", "HudLayer.State.cs");
        var unitBattlefieldCommands = ReviewGateSource.Read(root, "scripts", "core", "units", "runtime", "battlefield", "UnitBattlefield.Commands.cs");

        RequireText(battleRoot, "List<(Vector2 Position, float SightRange)> _unitBattlefieldVisionSourceBuffer", "BattleRoot vision source bridge must reuse storage.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapUnit> _minimapUnitBuffer", "BattleRoot minimap units must use reusable storage.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapUnit> _minimapUnitSecondaryBuffer", "BattleRoot minimap units must be double-buffered for redraw safety.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapBuilding> _minimapBuildingBuffer", "BattleRoot minimap buildings must use reusable storage.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapResource> _minimapResourceBuffer", "BattleRoot minimap resources must use reusable storage.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapAlertPing> _minimapAlertPingBuffer", "BattleRoot minimap alert pings must use reusable storage.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapAlertPing> _minimapAlertPingSecondaryBuffer", "BattleRoot minimap alert pings must be double-buffered for redraw safety.", result);
        RequireText(battleRoot, "List<HudLayer.AlertLine> _alertLineBuffer", "BattleRoot alert HUD sync must reuse alert line storage.", result);
        RequireText(battleRoot, "List<UnitInstance> _selectedUnitInstanceBuffer", "BattleRoot runtime selection HUD sync must reuse selected unit storage.", result);
        RequireText(battleRoot, "List<UnitModel> _selectedLegacyUnitBuffer", "BattleRoot legacy selection HUD sync must reuse selected unit storage.", result);
        RequireText(battleRoot, "List<BuildingModel> _selectedLegacyBuildingBuffer", "BattleRoot legacy selection HUD sync must reuse selected building storage.", result);
        RequireText(battleRoot, "List<int> _selectedProductionBuildingIdBuffer", "BattleRoot selected producer command-card sync must reuse selected building id storage.", result);
        RequireText(battleRoot, "SimEventSink _presentationEvents", "BattleRoot command acknowledgement feedback must use a SimEvent sink before drawing rings.", result);
        RequireText(battleRoot, "CommandAcknowledged = QueueCommandAcknowledgementEvent", "BattleRoot command acknowledgement callbacks must enqueue SimEvents instead of drawing rings directly.", result);
        RequireText(battleRoot, "_presentationEvents.Raise(new CommandAcknowledgedEvent", "BattleRoot command acknowledgement callbacks must raise CommandAcknowledgedEvent data.", result);
        RequireText(process, "DrainPresentationEvents();", "BattleRoot process must drain presentation SimEvents before drawing command acknowledgement rings.", result);
        RequireText(battleRoot, "_commandAcknowledgements.Add(acknowledgement.Kind, acknowledgement.Position)", "BattleRoot command acknowledgement rings must be applied from drained SimEvents.", result);
        RequireText(battleRoot, "PlayCommandAcknowledgementAudio(acknowledgement.AudioCue", "BattleRoot command audio cues must be applied from drained CommandAcknowledgedEvent data.", result);
        RequireText(ReviewGateSource.Read(root, "scripts", "controllers", "SelectionController.Commands.cs"), "AcknowledgeCommand(CommandAcknowledgementKind.Attack", "SelectionController command branches must send attack feedback through command acknowledgement events.", result);
        ForbidText(ReviewGateSource.Read(root, "scripts", "controllers", "SelectionController.Commands.cs"), "AudioCueRequested?.Invoke", "SelectionController command branches must not play command audio directly.", result);
        ForbidText(battleRoot, "CommandAcknowledged = AddCommandAcknowledgement", "BattleRoot command acknowledgement callbacks must not draw rings directly.", result);
        RequireText(battleRoot, "List<UnitInstance> _sandboxLaunchUnitBuffer", "BattleRoot sandbox launch selection must reuse unit storage.", result);
        RequireText(battleRoot, "List<int> _sandboxLaunchUnitIdBuffer", "BattleRoot sandbox launch selection must reuse id storage.", result);
        RequireText(battleRoot, "List<int> _debugPlayerAttackerIds", "Active battle perf setup must reuse player attacker id storage.", result);
        RequireText(battleRoot, "List<int> _debugEnemyAttackerIds", "Active battle perf setup must reuse enemy attacker id storage.", result);
        RequireText(process, "_unitBattlefieldVisionSourceBuffer.Clear();", "UnitBattlefieldVisionSources must clear and reuse the vision-source buffer.", result);
        RequireText(process, "foreach (var source in _unitBattlefield.VisionSources(PlayerSlotId.One))", "UnitBattlefieldVisionSources must copy vision sources explicitly.", result);
        RequireText(process, "_unitBattlefieldVisionSourceBuffer.Add((source.Position, source.SightRange));", "UnitBattlefieldVisionSources must fill the reusable vision-source buffer.", result);
        RequireText(process, "LiveUnitBattlefieldUnitCount()", "PerfHudCounts must use explicit runtime unit counting.", result);
        RequireText(process, "LiveLegacyUnitCount()", "PerfHudCounts must use explicit legacy unit counting.", result);
        RequireText(process, "LiveLegacyBuildingCount()", "PerfHudCounts must use explicit legacy building counting.", result);
        RequireText(process, "VisibleUnitViewCount()", "PerfHudCounts must use explicit visible unit view counting.", result);
        var hudSync = ReviewGateSource.Read(root, "scripts", "BattleRoot.HudSync.cs");
        var hudLayer = ReviewGateEvidence.ReadSourceWithPartials(Path.Combine(root, "scripts", "ui", "HudLayer.cs"));
        var hudBuild = ReviewGateSource.Read(root, "scripts", "ui", "hud", "HudLayer.Build.cs");
        var iconSummary = ReviewGateSource.Read(root, "scripts", "battle-root", "BattleRoot.SelectionIconSummary.cs");
        RequireText(hudBuild, "GameText.T(\"ui.tabs.command\")", "Production drawer tabs must expose the command build category.", result);
        RequireText(hudBuild, "GameText.T(\"ui.tabs.power\")", "Production drawer tabs must expose the power build category.", result);
        RequireText(hudBuild, "GameText.T(\"ui.tabs.economy\")", "Production drawer tabs must expose the economy build category.", result);
        RequireText(hudBuild, "GameText.T(\"ui.tabs.infantry\")", "Production drawer tabs must expose the infantry build category.", result);
        RequireText(hudBuild, "GameText.T(\"ui.tabs.vehicle\")", "Production drawer tabs must expose the vehicle build category.", result);
        RequireText(hudBuild, "GameText.T(\"ui.tabs.defense\")", "Production drawer tabs must expose the defense build category.", result);
        RequireText(hudBuild, "GameText.T(\"ui.tabs.air\")", "Production drawer tabs must expose the air build category.", result);
        RequireText(hudBuild, "GameText.T(\"ui.tabs.naval\")", "Production drawer tabs must expose the naval build category.", result);
        RequireText(hudBuild, "BuildCategory.Defense", "Production drawer tabs must carry typed build categories into HUD actions.", result);
        RequireText(hudLayer, "List<ProductionTab> _productionTabs", "Production drawer tabs must retain tab controls so selected state can update after clicks.", result);
        RequireText(hudLayer, "SelectProductionTab(category);", "Production drawer tabs must update the visible selected tab before routing build placement.", result);
        RequireText(hudLayer, "tab.SetSelected(tab.Category == category);", "Production drawer tabs must redraw selected state from the last requested build category.", result);
        RequireText(hudLayer, "Action<string, int?>? BuildKindRequested", "HudLayer must expose build-kind catalog intents with optional Build provider lane selection.", result);
        RequireText(battleRoot, "BuildKindRequested = OnBuildKindRequested", "BattleRoot must wire build option cards into build placement.", result);
        var buildPlacement = ReviewGateSource.Read(root, "scripts", "controllers", "BuildPlacementController.cs");
        RequireText(buildPlacement, "public bool SelectBuildKind(string kind, int? constructionProviderId = null)", "Build placement controller must accept optional specific construction provider lane selection.", result);
        RequireText(buildPlacement, "_selectedConstructionProviderId = constructionProviderId", "Build placement controller must retain the selected Build provider for ticket queuing.", result);
        RequireText(hudSync, "SetBuildCardState(_state.BuildOptionSnapshots(ProceduralRts.Core.Owner.Player))", "BattleRoot must feed build option snapshots into the HUD catalog.", result);
        RequireText(hudLayer, "List<BuildOptionSnapshot> _buildCardStates", "HudLayer build catalog cards must keep reusable build option state storage.", result);
        RequireText(hudState, "Label _catalogOverviewValue", "HudLayer must own a compact catalog overview readout.", result);
        RequireText(hudBuild, "Name = \"CatalogOverview\"", "Right command panel catalog overview must expose a stable node.", result);
        RequireText(hudLayer, "RefreshCatalogOverview()", "Right command panel must refresh the catalog overview when page state changes.", result);
        RequireText(hudLayer, "CatalogOverviewConstructionLaneCount()", "Build catalog overview must summarize construction provider lane count.", result);
        RequireText(hudLayer, "CatalogOverviewProductionLaneCount()", "Train catalog overview must summarize visible provider lane count.", result);
        RequireText(hudLayer, "_selectedCatalogMode == CatalogModeKind.Build", "HudLayer command-card refresh must branch build cards from train cards by catalog mode.", result);
        RequireText(hudLayer, "state.Category != _selectedBuildCategory", "Build option cards must filter by the selected build category.", result);
        RequireText(hudLayer, "_visibleBuildCardStates.Count >= 12", "Build option cards must keep the fixed-grid cap used by the right panel.", result);
        RequireText(hudLayer, "button.SetBuildState(state, disabledReason)", "Build option cards must render build snapshot state and disabled reasons explicitly.", result);
        RequireText(hudLayer, "BuildKindRequested?.Invoke(button.BuildKind, SelectedConstructionProviderId())", "Build option cards must emit build-kind intents with selected construction provider lanes instead of production requests.", result);
        ForbidText(hudLayer, "BuildCategoryRequested?.Invoke(category);", "Build category tabs must filter build cards without arming placement.", result);
        ForbidText(hudLayer, "Action<BuildCategory>? BuildCategoryRequested", "HudLayer must not expose a stale build-category placement intent.", result);
        ForbidText(battleRoot, "BuildCategoryRequested = OnBuildCategoryRequested", "BattleRoot must not wire category tabs into build placement.", result);
        ForbidText(ReviewGateSource.Read(root, "scripts", "controllers", "BuildPlacementController.cs"), "public bool SelectBuildCategory(BuildCategory category)", "Build placement controller must use build-kind card intents, not category intents.", result);
        RequireText(hudBuild, "RibbonCancelProduction", "Command ribbon sell action must expose a stable node.", result);
        RequireText(hudLayer, "Action? SellOrCancelRequested", "HudLayer must expose the command-ribbon sell-or-cancel request.", result);
        RequireText(hudBuild, "ribbonCancel.Pressed += () => SellOrCancelRequested?.Invoke();", "Command ribbon sell action must route through the sell-or-cancel request path.", result);
        RequireText(hudBuild, "_cancelProduction.Pressed += () => CancelProductionRequested?.Invoke();", "Right-side queue cancel must stay on the production cancel request path.", result);
        RequireText(battleRoot, "SellOrCancelRequested = OnSellOrCancelRequested", "BattleRoot must wire the command-ribbon sell-or-cancel request.", result);
        RequireText(battleRoot, "_unitBattlefield.SellSelectedBuildings", "BattleRoot sell-or-cancel request must sell selected buildings before falling back to production cancel.", result);
        RequireText(ReviewGateSource.Read(root, "scripts", "core", "units", "runtime", "battlefield", "UnitBattlefield.BuildingSell.cs"), "BuildSpecCatalog.For(identity.Kind)", "Selected building sell must refund from the build spec instead of production cancel constants.", result);
        RequireText(ReviewGateSource.Read(root, "scripts", "core", "units", "runtime", "UnitBattlefieldBuildingDeathInfo.cs"), "UnitBattlefieldBuildingRemovalCause", "Runtime building removals must expose a removal cause.", result);
        RequireText(ReviewGateSource.Read(root, "scripts", "core", "units", "runtime", "UnitBattlefieldBuildingDeathInfo.cs"), "Sold", "Runtime building removals must distinguish sold structures from destroyed structures.", result);
        var selectionController = ReviewGateEvidence.ReadSourceWithPartials(Path.Combine(root, "scripts", "controllers", "SelectionController.cs"));
        RequireText(hudLayer, "Action? RepairRequested", "HUD must expose a repair request for the command-ribbon repair button.", result);
        RequireText(hudBuild, "Name = \"RibbonRepair\"", "Command ribbon repair action must expose a stable node.", result);
        RequireText(hudBuild, "ribbonRepair.Pressed += () => RepairRequested?.Invoke();", "Command ribbon repair action must route through the repair request path.", result);
        RequireText(battleRoot, "RepairRequested = OnRepairRequested", "BattleRoot must wire the HUD repair request into selection commands.", result);
        RequireText(hudSync, "_selection.ArmRepairCommand();", "BattleRoot repair request must arm the SelectionController repair command mode.", result);
        RequireText(selectionController, "public void ArmRepairCommand()", "SelectionController must expose one-shot repair command arming for the command ribbon.", result);
        RequireText(selectionController, "FinishRuntimeRepairCommand(ScreenToWorld(screenPoint), acknowledgeInvalidAtTarget: true)", "Armed repair mode must finish through the existing runtime repair command path on click.", result);
        RequireText(hudLayer, "Action? RallyRequested", "HudLayer must expose the command-ribbon rally request.", result);
        RequireText(hudBuild, "RibbonSetRally", "Command ribbon rally action must expose a stable node.", result);
        RequireText(hudBuild, "ribbonRally.Pressed += () => RallyRequested?.Invoke();", "Command ribbon rally action must route through the rally request path.", result);
        RequireText(battleRoot, "RallyRequested = OnRallyRequested", "BattleRoot must wire the HUD rally request into selection commands.", result);
        RequireText(hudSync, "_selection.ArmRallyCommand();", "BattleRoot rally request must arm the SelectionController rally command mode.", result);
        RequireText(selectionController, "public void ArmRallyCommand()", "SelectionController must expose one-shot rally command arming for the command ribbon.", result);
        RequireText(selectionController, "FinishArmedRallyCommand(mouse.Position)", "Armed rally mode must finish through the selected-building rally backend on click.", result);
        RequireText(hudState, "Label _sandboxStateHashValue", "Sandbox developer HUD must own a state-hash readout label.", result);
        RequireText(hudBuild, "Name = \"SandboxStateHash\"", "Sandbox developer HUD must expose the state-hash readout as a stable node.", result);
        RequireText(sandbox, "SandboxDebugOverlayFlag.StateHash", "Sandbox state-hash readout must be gated by the debug overlay flag.", result);
        RequireText(sandbox, "_unitBattlefield.EntityWorld.DeterministicStateHash()", "Sandbox state-hash readout must use the live runtime EntityWorld hash.", result);
        RequireText(process, "RefreshSandboxStateHash();", "BattleRoot process must refresh sandbox state-hash overlay state.", result);
        RequireText(hudSync, "CollectSelectedProductionBuildingIds();", "Runtime command-card refresh must collect selected building ids once for command-card and queue sync.", result);
        RequireText(hudSync, "RuntimeProductionCommandCardStates(_selectedProductionBuildingIdBuffer)", "Runtime command-card refresh must route through selected-producer state selection.", result);
        RequireText(hudSync, "_unitBattlefield.ProductionDesignOptionStatesForSelectedProducers", "Runtime command-card refresh must use selected producer production options when available.", result);
        RequireText(hudSync, "RuntimeProductionQueueSummary(_selectedProductionBuildingIdBuffer, out var canCancel)", "Runtime queue summary refresh must route through selected-producer queue state selection.", result);
        RequireText(hudSync, "_unitBattlefield.ProductionQueueSummaryForSelectedProducers", "Runtime queue summary refresh must use selected producer queues when available.", result);
        RequireText(hudSync, "_unitBattlefield.CancelFirstProductionForSelectedProducers", "Runtime cancel button must cancel selected producer queues when available.", result);
        RequireText(hudSync, "if (hasSelectedProducers)", "Runtime producer HUD sync must fall back to aggregate state only when no selected producer exists.", result);
        RequireText(hudLayer, "List<ProductionProviderLaneState> _productionProviderLaneStates", "Train catalog provider lanes must keep reusable lane state storage.", result);
        RequireText(hudLayer, "List<ProductionProviderLaneState> _constructionProviderLaneStates", "Build catalog construction provider lanes must keep separate reusable lane state storage.", result);
        RequireText(hudLayer, "private partial class ProductionProviderLaneButton : Button", "Train catalog provider lanes must render through stable lane buttons.", result);
        RequireText(hudLayer, "Name = $\"ProductionProviderLane{index}\"", "Train provider lane buttons must expose stable node names for QA.", result);
        RequireText(hudBuild, "AddProductionProviderLaneButton(_rightRail, index)", "Train provider lanes must live in the right rail instead of compressing the 12-slot card grid.", result);
        RequireText(hudBuild, "Name = \"ProviderLaneSummary\"", "Train provider lane summary must expose a stable node name for QA.", result);
        RequireText(hudLayer, "RefreshProductionProviderLaneSummary()", "Train provider lane selection/state changes must refresh the provider detail summary.", result);
        RequireText(hudLayer, "SetConstructionProviderLaneState(IReadOnlyList<ProductionProviderLaneState> states)", "HUD must accept Build-mode construction provider lane read models separately from Train lanes.", result);
        RequireText(hudLayer, "SelectConstructionProviderLane(state)", "Build provider lane clicks must update construction lane selection without changing Train provider selection.", result);
        RequireText(hudLayer, "private int? SelectedConstructionProviderId()", "Build provider lanes must expose selected specific-provider ids for Build card routing.", result);
        RequireText(hudLayer, "button.SetState(state, IsConstructionProviderLaneSelected(state), state.Available, constructionMode: true)", "Build catalog mode must render construction provider lanes in the right rail.", result);
        RequireText(hudLayer, "ui.constructionProviderLane.tooltip", "Build provider lane tooltips must use construction-specific copy.", result);
        RequireText(hudLayer, "ProviderLaneSummaryText(state)", "Train provider lane summary must render selected provider count, queue count, progress, and availability.", result);
        RequireText(hudLayer, "ProviderLaneSummaryDisabledReason(state.DisabledReasonKey)", "Train provider lane summary must use rail-safe disabled reason codes.", result);
        RequireText(hudLayer, "ProductionDesignRequested?.Invoke(button.UnitDesignId, () => SelectedProductionProviderId(button.UnitDesignId), ProductionRequestCount())", "Shift-click train cards must pass a bounded production request count while preserving provider lane selection.", result);
        RequireText(hudLayer, "ProductionRequested?.Invoke(button.Kind, ProductionRequestCount())", "Legacy production card requests must pass the same Shift batch count path.", result);
        RequireText(hudLayer, "Input.IsKeyPressed(Key.Shift) ? ShiftProductionBatchCount : 1", "HUD train cards must keep single-click unchanged and Shift-click bounded.", result);
        RequireText(hudLayer, "Action<string, int>? ProductionRepeatRequested", "HUD must expose a selected-provider repeat-production request.", result);
        RequireText(hudLayer, "Name = \"RepeatProduction\"", "Right Train controls must expose a stable repeat-production toggle node.", result);
        RequireText(hudLayer, "FocusRepeatProductionDesign(button.UnitDesignId)", "Train card hover/click must establish the repeat-production target context.", result);
        RequireText(hudLayer, "CurrentProductionProviderLaneState() is not { Scope: ProductionProviderLaneScope.Specific", "Repeat production must require a specific provider lane.", result);
        RequireText(hudLayer, "State.RepeatOutputSpecId", "Provider lane controls must surface the armed repeat unit state.", result);
        RequireText(battleRoot, "internal const int ShiftProductionBatchCount = 5", "BattleRoot must expose the bounded Shift production batch count.", result);
        RequireText(battleRoot, "ProductionBatchStatus(queued, attempts, status)", "BattleRoot production requests must summarize Shift batches after existing command submission.", result);
        RequireText(battleRoot, "TrySubmitProductionDesignRequest(designId, providerIdSelector(), out status)", "Train-card Shift batches must resolve provider lanes for each queued attempt.", result);
        RequireText(hudLayer, "NextAllProductionProviderId(spec.Production.ProducerKind)", "All provider lane clicks must distribute repeated train commands across valid providers.", result);
        RequireText(hudSync, "_hud.SetProductionProviderLaneState(_unitBattlefield.ProductionProviderLaneStates(PlayerSlotId.One))", "BattleRoot must feed runtime production provider lane state into the HUD.", result);
        RequireText(hudSync, "_hud.SetConstructionProviderLaneState(_unitBattlefield.ConstructionProviderLaneStates(PlayerSlotId.One))", "BattleRoot must feed runtime construction provider lane state into the HUD.", result);
        RequireText(hudSync, "_buildPlacement.SelectBuildKind(kind, constructionProviderId)", "BattleRoot must hand selected Build provider lanes into build placement.", result);
        RequireText(battleRoot, "ProductionRepeatRequested = OnProductionRepeatRequested", "BattleRoot must wire the Train repeat toggle from HUD.", result);
        RequireText(battleRoot, "ToggleRepeatProductionForProvider", "BattleRoot must route repeat production through the UnitBattlefield provider helper.", result);
        RequireText(battleRoot, "TryCreateProductionDesignPayloadForProvider", "BattleRoot must route specific provider lane production through a scoped payload helper.", result);
        RequireText(ReviewGateSource.Read(root, "scripts", "core", "units", "runtime", "battlefield", "UnitBattlefield.ProductionOptions.cs"), "public IReadOnlyList<ProductionProviderLaneState> ProductionProviderLaneStates(PlayerSlotId playerSlotId)", "UnitBattlefield must expose production provider lane read models without HUD hard-coding provider names.", result);
        RequireText(ReviewGateSource.Read(root, "scripts", "core", "units", "runtime", "battlefield", "UnitBattlefield.ProductionOptions.cs"), "BuildingProductionRepeatOutputSpecId(building.Id)", "Production provider lanes must carry armed repeat state from the runtime queue.", result);
        RequireText(ReviewGateSource.Read(root, "scripts", "core", "units", "runtime", "battlefield", "UnitBattlefield.ProductionRally.cs"), "SetRepeatProductionEntityCommand", "UnitBattlefield repeat toggle must reuse the deterministic repeat-production command.", result);
        RequireText(ReviewGateSource.Read(root, "scripts", "core", "units", "runtime", "battlefield", "UnitBattlefield.ConstructionProviderLanes.cs"), "public IReadOnlyList<ProductionProviderLaneState> ConstructionProviderLaneStates(PlayerSlotId playerSlotId)", "UnitBattlefield must expose construction provider lane read models without HUD hard-coding provider names.", result);
        RequireText(ReviewGateSource.Read(root, "scripts", "core", "units", "runtime", "battlefield", "UnitBattlefield.ConstructionTickets.cs"), "ConstructionSubjectEntities(playerSlotId, spec, constructionProviderId)", "Construction ticket queuing must honor specific Build provider lane selection.", result);
        RequireText(ReviewGateSource.Read(root, "scripts", "core", "units", "runtime", "battlefield", "UnitBattlefield.PlayerCommandPayloads.cs"), "TryCreateProductionDesignPayloadForProvider", "UnitBattlefield must expose a specific-provider production payload helper.", result);
        var englishProviderText = ReviewGateSource.Read(root, "scripts", "core", "localization", "GameText.English.cs");
        var chineseProviderText = ReviewGateSource.Read(root, "scripts", "core", "localization", "GameText.ChineseSimplified.cs");
        RequireText(englishProviderText, "[\"ui.providerLane.summaryOk\"] = \"OK\"", "English provider summary must use a rail-safe OK code.", result);
        RequireText(englishProviderText, "[\"ui.providerLane.summaryOffline\"] = \"OFF\"", "English provider summary must use a rail-safe offline code.", result);
        RequireText(englishProviderText, "[\"ui.constructionProviderLane.auto\"]", "English Build provider lane Auto label must exist.", result);
        RequireText(englishProviderText, "[\"ui.constructionProviderLane.tooltip\"]", "English Build provider lane tooltip must use construction-specific copy.", result);
        RequireText(englishProviderText, "[\"production.repeatEnabled\"]", "English repeat-production status text must exist.", result);
        ForbidText(englishProviderText, "[\"ui.providerLane.available\"]", "Provider summary must not use long availability text in the narrow right rail.", result);
        RequireText(chineseProviderText, "[\"ui.providerLane.summaryOk\"]", "Chinese provider summary must use a rail-safe OK code.", result);
        RequireText(chineseProviderText, "[\"ui.providerLane.summaryOffline\"]", "Chinese provider summary must use a rail-safe offline code.", result);
        RequireText(chineseProviderText, "[\"ui.constructionProviderLane.auto\"]", "Chinese Build provider lane Auto label must exist.", result);
        RequireText(chineseProviderText, "[\"ui.constructionProviderLane.tooltip\"]", "Chinese Build provider lane tooltip must use construction-specific copy.", result);
        RequireText(chineseProviderText, "[\"production.repeatEnabled\"]", "Chinese repeat-production status text must exist.", result);
        ForbidText(chineseProviderText, "[\"ui.providerLane.available\"]", "Provider summary must not use long availability text in the narrow right rail.", result);
        RequireText(hudSync, "CollectSelectedUnitInstances(PlayerSlotId.One, _selectedUnitInstanceBuffer)", "Runtime selection HUD sync must fill the reusable selected-unit buffer.", result);
        RequireText(hudSync, "private void CollectSelectedUnitInstances(PlayerSlotId playerSlotId, List<UnitInstance> result)", "Runtime selection HUD sync must expose a reusable selected-unit collector.", result);
        RequireText(hudSync, "spec.TryGetAbility(AbilityKind.ShieldField, out var shieldField)", "Runtime selected-unit details must surface ShieldField units from authored AbilitySpec data.", result);
        RequireText(hudSync, "GameText.Format(\n                \"ui.detail.shieldField\"", "Runtime selected-unit details must render localized ShieldField radius and absorb text.", result);
        RequireText(hudSync, "ShieldFieldAbsorbLabel(shieldField.Value)", "Runtime selected-unit details must derive ShieldField absorb presentation from ability values.", result);
        RequireText(hudSync, "CollectSelectedLegacyUnits(_selectedLegacyUnitBuffer)", "Legacy selection HUD sync must fill the reusable selected-unit buffer.", result);
        RequireText(hudSync, "CollectSelectedLegacyBuildings(_selectedLegacyBuildingBuffer)", "Legacy selection HUD sync must fill the reusable selected-building buffer.", result);
        RequireText(hudSync, "foreach (var unit in units)", "Runtime selection HUD group stats must use explicit loops.", result);
        RequireText(hudSync, "foreach (var building in buildings)", "Runtime building selection HUD group stats must use explicit loops.", result);
        RequireText(hudSync, "foreach (var unit in selectedUnits)", "Legacy selection HUD unit stats must use explicit loops.", result);
        RequireText(hudSync, "foreach (var building in selectedBuildings)", "Legacy selection HUD building stats must use explicit loops.", result);
        RequireText(battleRoot, "for (var index = 1; index < selectedUnits.Count; index++)", "SelectedUniformStance must scan selected units without LINQ All.", result);
        RequireText(alerts, "HasSelectedLegacyBuildings()", "Command preview must use the explicit legacy building selection scan.", result);
        RequireText(alerts, "HasLegacyPlayerPowerPlant()", "Power alert must use the explicit legacy power-building scan.", result);
        RequireText(alerts, "IdleLegacyHarvesterCount()", "Idle harvester alert must use an explicit legacy harvester count scan.", result);
        RequireText(alerts, "RuntimeIdleHarvesterCount(out firstIdleHarvesterWorldPosition)", "Runtime idle harvester alerts must count runtime harvesters and capture their first world position.", result);
        RequireText(alerts, "AddAlert(\n            AlertKind.Harvester", "Idle harvester alerts must keep using the standard bounded alert insertion path.", result);
        RequireText(alerts, "firstIdleHarvesterWorldPosition);", "Idle harvester alerts must carry a world position for minimap pings and Space jump.", result);
        RequireText(alerts, "AddAlert(AlertKind.Power, powerStable ? GameText.T(\"ui.alert.powerStable\") : GameText.T(\"ui.alert.powerOffline\"), PowerAlertWorldPosition())", "Power alerts must carry a stable world position for minimap pings and Space jump.", result);
        RequireText(alerts, "IsInsufficientCreditsStatus(status)", "Status alert routing must detect insufficient-credit command failures explicitly.", result);
        RequireText(alerts, "TryUseAlertCooldown(\"status:insufficient-credits\", InsufficientCreditsAlertCooldown)", "Insufficient-credit alerts must be throttled by one stable key instead of the full status text.", result);
        RequireText(alerts, "AddAlert(AlertKind.Economy, GameText.T(\"ui.alert.insufficientCredits\"))", "Insufficient-credit failures must surface a localized economy alert.", result);
        RequireText(alerts, "ContainsLocalizedNeedCreditsPrefix(status, \"ui.needCredits\")", "Insufficient-credit detection must cover build placement credit failures.", result);
        RequireText(alerts, "ContainsLocalizedNeedCreditsPrefix(status, \"production.needCredits\")", "Insufficient-credit detection must cover production credit failures.", result);
        RequireText(alerts, "private Vector2? PowerAlertWorldPosition()", "BattleRoot alerts must expose a power-alert position helper.", result);
        RequireText(alerts, "private Vector2? RuntimePowerAlertWorldPosition()", "Runtime power alerts must compute a live player building position.", result);
        RequireText(alerts, "private Vector2? LegacyPowerAlertWorldPosition()", "Legacy power alerts must compute a live player building position.", result);
        RequireText(alerts, "building.Kind == BuildingDesignIds.PowerPlant", "Power alert position must prefer a live player PowerPlant.", result);
        RequireText(alerts, "private bool HasSelectedLegacyBuildings()", "BattleRoot alerts must expose the legacy selected-building scan helper.", result);
        RequireText(alerts, "private bool HasLegacyPlayerPowerPlant()", "BattleRoot alerts must expose the legacy power scan helper.", result);
        RequireText(alerts, "private int IdleLegacyHarvesterCount()", "BattleRoot alerts must expose the legacy idle harvester count scan helper.", result);
        RequireText(unitBattlefieldCommands, "public int IdleHarvesterCount(PlayerSlotId playerSlotId, out Vector2? firstWorldPosition)", "UnitBattlefield must expose an allocation-free idle harvester alert snapshot.", result);
        RequireText(unitBattlefieldCommands, "firstWorldPosition ??= unit.Position;", "Runtime idle harvester snapshots must capture the first alert jump position.", result);
        RequireText(battleRoot, "CollectActiveBattlePerfAttackers(PlayerSlotId.One, _debugPlayerAttackerIds)", "Active battle perf setup must fill player attacker ids explicitly.", result);
        RequireText(battleRoot, "CollectActiveBattlePerfAttackers(PlayerSlotId.Two, _debugEnemyAttackerIds)", "Active battle perf setup must fill enemy attacker ids explicitly.", result);
        RequireText(battleRoot, "var designIds = new string[count];", "BattleRoot debug design-id readout must build an explicit stable snapshot.", result);
        RequireText(battleRoot, "designIds[index++] = unit.Spec.Id;", "BattleRoot debug design-id readout must fill snapshots with an explicit scan.", result);
        RequireText(sandbox, "CollectSandboxLaunchSelectionIds();", "Sandbox launch must fill reusable selected-unit id storage.", result);
        RequireText(sandbox, "_sandboxLaunchUnitBuffer.Sort(CompareSandboxLaunchUnits)", "Sandbox launch selection must sort reusable unit storage in place.", result);
        RequireText(sandbox, "NextSandboxBuildingTargetId()", "Sandbox structure spawn must compute next building id with an explicit scan.", result);
        RequireText(iconSummary, "List<SelectionIconSummaryEntry> _selectionIconSummaryEntries", "Selection icon summaries must reuse aggregation storage.", result);
        RequireText(iconSummary, "List<HudLayer.SelectionIconItem> _selectionIconSummarySecondaryBuffer", "Selection icon summaries must double-buffer HUD-owned item storage.", result);
        RequireText(iconSummary, "NextSelectionIconSummaryBuffer()", "Selection icon summaries must acquire reusable HUD item storage.", result);
        RequireText(iconSummary, "_useSecondarySelectionIconSummaryBuffer", "Selection icon summaries must alternate HUD item buffers.", result);
        RequireText(battleRoot, "FillMinimapUnits(units)", "RefreshMinimap must fill the reusable unit buffer.", result);
        RequireText(battleRoot, "FillUnitBattlefieldMinimapBuildings(buildings)", "RefreshMinimap must fill the reusable runtime building buffer.", result);
        RequireText(battleRoot, "FillMinimapResources(resources)", "RefreshMinimap must fill the reusable resource buffer.", result);
        RequireText(battleRoot, "FillMinimapAlertPings(alertPings)", "RefreshMinimap must fill active alert pings from reusable alert storage.", result);
        RequireText(minimap, "for (var index = 0; index < _alerts.Count; index++)", "BattleRoot minimap alert pings must scan active alerts explicitly.", result);
        RequireText(minimap, "alert.WorldPosition is not { } position", "BattleRoot minimap alert pings must come from world-positioned alerts.", result);
        RequireText(minimap, "result.Add(new HudLayer.MinimapAlertPing", "BattleRoot minimap alert pings must copy HUD presentation data explicitly.", result);
        RequireText(hudState, "IReadOnlyList<MinimapAlertPing>? alertPings = null", "HudLayer minimap state must accept active alert pings as optional presentation data.", result);
        RequireText(hudState, "_minimapSurface.AlertPings = alertPings ?? []", "HudLayer minimap state must keep alert ping assignment allocation-free.", result);
        RequireText(minimap, "foreach (var unit in _state.Units)", "BattleRoot minimap units must use an explicit scan.", result);
        RequireText(minimap, "foreach (var building in projections)", "BattleRoot runtime minimap buildings must copy projections explicitly.", result);
        RequireText(minimap, "foreach (var resource in pips)", "BattleRoot minimap resources must copy pips explicitly.", result);
        RequireText(hudState, "public readonly record struct MinimapAlertPing", "HudLayer must expose a compact minimap alert ping presentation record.", result);
        RequireText(alerts, "_alertLineBuffer.Clear();", "RefreshAlerts must clear and reuse the alert line buffer.", result);
        RequireText(alerts, "_alertLineBuffer.Count < 4", "RefreshAlerts must cap HUD alert lines without LINQ Take.", result);
        RequireText(alerts, "_hud.SetAlerts(_alertLineBuffer)", "RefreshAlerts must pass reusable alert lines to HudLayer.", result);
        RequireText(alerts, "private bool TryJumpToLatestPositionedAlert()", "BattleRoot alerts must expose a bounded latest-positioned-alert jump helper.", result);
        RequireText(alerts, "OnMinimapJumpRequested(worldPosition);", "Alert hotkey jump must reuse the existing minimap camera focus path.", result);
        RequireText(process, "key.Keycode == Key.Space && TryJumpToLatestPositionedAlert()", "BattleRoot input must route Space to the latest positioned alert before sandbox-only debug keys.", result);
        RequireText(battleRoot, "GameText.Format(\"ui.unit.destroyed\", UnitDesignCatalog.Spec(death.DesignId).Label)", "Runtime player unit deaths must add localized unit-lost alert text.", result);
        RequireText(battleRoot, "AddAlert(AlertKind.Combat, GameText.Format(\"ui.unit.destroyed\", UnitDesignCatalog.Spec(death.DesignId).Label), death.Position)", "Runtime player unit-lost alerts must carry world positions for minimap pings and Space jump.", result);
        RequireText(battleRoot, "private const float ProductionAlertCooldown", "Production-complete alerts must expose a bounded anti-spam cooldown.", result);
        RequireText(alerts, "private void AddProductionCompleteAlert(string designId, string label, Vector2 worldPosition)", "Production-complete alerts must use a focused positioned-alert helper.", result);
        RequireText(alerts, "TryUseAlertCooldown($\"production-complete:{designId}\", ProductionAlertCooldown)", "Production-complete alerts must be throttled per produced design.", result);
        RequireText(alerts, "AddAlert(AlertKind.Production, GameText.Format(\"ui.production.deployed\", label), worldPosition)", "Production-complete alerts must keep using the positioned production alert path.", result);
        RequireText(battleRoot, "AddProductionCompleteAlert(item.DesignId, spec.Label, building.Position)", "Runtime production completion must carry the producer position into the alert stack.", result);
        RequireText(battleRoot, "AddProductionCompleteAlert(completed.DesignId, spec.Label, building.Position)", "Legacy production completion must keep the same positioned alert path.", result);
        RequireText(hudState, "List<ProductionOptionState> _commandCardStates", "HudLayer command-card refresh must reuse visible state storage.", result);
        RequireText(hudState, "HashSet<string> _commandCardActiveIds", "HudLayer command-card refresh must reuse active id storage.", result);
        RequireText(hudState, "List<string> _commandCardStaleIds", "HudLayer command-card refresh must reuse stale id storage.", result);
        RequireText(hudState, "_commandCardStates.Add(state)", "HudLayer command-card refresh must fill reusable state storage.", result);
        RequireText(hudState, "_commandCardStaleIds.Add(key)", "HudLayer command-card refresh must collect stale keys before removing buttons.", result);
        var hudCommandControls = ReviewGateSource.Read(root, "scripts", "ui", "hud", "HudLayer.CommandControls.cs");
        RequireText(hudCommandControls, "ProducerShortCode = BuildSpecCatalog.For(state.ProducerKind).ShortCode", "Train catalog cards must surface the source producer as compact metadata.", result);
        RequireText(hudCommandControls, "RoleGlyph = state.RoleGlyph == IconGlyph.None ? state.Icon : state.RoleGlyph", "Train catalog cards must surface unit role glyphs separately from the main unit icon.", result);
        RequireText(hudCommandControls, "private bool IsTrainCard => !string.IsNullOrWhiteSpace(UnitDesignId)", "Train catalog card metadata must stay scoped to unit production cards.", result);
        RequireText(hudCommandControls, "DrawTrainCardMetadata(size)", "Train catalog cards must render source/role metadata in the card surface.", result);
        RequireText(hudCommandControls, "ProducerShortCode = \"\";", "Build cards must clear train-only producer metadata.", result);
        RequireText(hudCommandControls, "Duration = 0;", "Build cards must clear train-only duration metadata.", result);
        RequireText(hudCommandControls, "CompactCardText(_disabledReason, 11)", "Train catalog cards must surface compact disabled reasons without expanding the layout.", result);
        ForbidText(minimap, ".ToList()", "BattleRoot minimap sync must not allocate materialized lists.", result);
        ForbidText(minimap, ".Select(", "BattleRoot minimap sync must not allocate LINQ projection chains.", result);
        ForbidText(minimap, ".Where(", "BattleRoot minimap sync must not allocate LINQ filter chains.", result);
        ForbidText(process, ".Select(source => (source.Position, source.SightRange))", "BattleRoot vision source bridge must not allocate LINQ projection iterators.", result);
        ForbidText(process, "_unitBattlefield.Units.Count(unit => unit.Hp > 0)", "PerfHudCounts must not allocate runtime live-unit count iterators.", result);
        ForbidText(process, "_state.Units.Count(unit => unit.Hp > 0)", "PerfHudCounts must not allocate legacy live-unit count iterators.", result);
        ForbidText(process, "_state.Buildings.Count(building => building.Hp > 0)", "PerfHudCounts must not allocate legacy live-building count iterators.", result);
        ForbidText(process, "_unitInstanceViews.Values.Count(view => view.Visible)", "PerfHudCounts must not allocate runtime visible-view count iterators.", result);
        ForbidText(process, "_unitViews.Values.Count(view => view.Visible)", "PerfHudCounts must not allocate legacy visible-view count iterators.", result);
        ForbidText(battleRoot, "_state.SelectedUnits().Count()", "BattleRoot selected-unit readouts must use explicit selected-unit count scans.", result);
        ForbidText(hudSync, "_unitBattlefield.SelectedUnits(PlayerSlotId.One).ToList()", "Runtime selection HUD sync must not materialize selected UnitBattlefield units.", result);
        ForbidText(hudSync, "_state.SelectedUnits().ToList()", "Legacy selection HUD sync must not materialize selected GameState units.", result);
        ForbidText(hudSync, "_state.SelectedBuildings().ToList()", "Legacy selection HUD sync must not materialize selected GameState buildings.", result);
        ForbidText(hudSync, "var combatUnits = units.Count(unit =>", "Runtime selection HUD group stats must not allocate LINQ count iterators.", result);
        ForbidText(hudSync, "var economyUnits = units.Count(unit =>", "Runtime selection HUD group stats must not allocate LINQ count iterators.", result);
        ForbidText(hudSync, "var cargo = units.Sum(unit => unit.Cargo)", "Runtime selection HUD group stats must not allocate LINQ sum iterators.", result);
        ForbidText(hudSync, "var avgHealth = units.Average(unit =>", "Runtime selection HUD group stats must not allocate LINQ average iterators.", result);
        ForbidText(hudSync, "buildings.Average(building =>", "Runtime building selection HUD group stats must not allocate LINQ average iterators.", result);
        ForbidText(hudSync, "selectedUnits.Count(unit =>", "Legacy selection HUD group stats must not allocate LINQ count iterators.", result);
        ForbidText(hudSync, "selectedUnits.Sum(unit => unit.Cargo)", "Legacy selection HUD group stats must not allocate LINQ sum iterators.", result);
        ForbidText(hudSync, "selectedUnits.Average(", "Legacy selection HUD group stats must not allocate LINQ average iterators.", result);
        ForbidText(hudSync, "selectedBuildings.Average(", "Legacy selection HUD group stats must not allocate LINQ average iterators.", result);
        ForbidText(battleRoot, ".All(unit => unit.Stance == stance)", "SelectedUniformStance must not allocate LINQ All iterators.", result);
        ForbidText(battleRoot, "var playerAttackers = _unitBattlefield.Units", "Active battle perf setup must not allocate player attacker LINQ chains.", result);
        ForbidText(battleRoot, "var enemyAttackers = _unitBattlefield.Units", "Active battle perf setup must not allocate enemy attacker LINQ chains.", result);
        ForbidText(battleRoot, ".Where(unit => unit.PlayerSlotId == PlayerSlotId.One && unit.Hp > 0 && unit.WeaponMounts.Count > 0)", "Active battle perf setup must scan player attackers explicitly.", result);
        ForbidText(battleRoot, ".Where(unit => unit.PlayerSlotId == PlayerSlotId.Two && unit.Hp > 0 && unit.WeaponMounts.Count > 0)", "Active battle perf setup must scan enemy attackers explicitly.", result);
        ForbidText(battleRoot, ".Select(unit => unit.Spec.Id)", "BattleRoot debug design-id readout must not allocate LINQ projection chains.", result);
        ForbidText(hudSync, ".GroupBy(", "Selection HUD sync must not allocate icon summary grouping chains.", result);
        ForbidText(hudSync, ".ToList()", "Selection HUD sync must not materialize icon summary lists.", result);
        ForbidText(iconSummary, ".GroupBy(", "Selection icon summaries must not allocate grouping chains.", result);
        ForbidText(iconSummary, ".OrderBy", "Selection icon summaries must sort reusable entries in place.", result);
        ForbidText(iconSummary, ".Select(", "Selection icon summaries must not allocate projection chains.", result);
        ForbidText(iconSummary, ".Distinct()", "Selection icon summaries must track faction uniformity explicitly.", result);
        ForbidText(iconSummary, ".ToList()", "Selection icon summaries must not allocate materialized lists.", result);
        ForbidText(alerts, ".OrderByDescending(alert => alert.CreatedAt)", "RefreshAlerts must not allocate ordered alert queries.", result);
        ForbidText(alerts, ".Take(4)", "RefreshAlerts must not allocate LINQ take queries.", result);
        ForbidText(alerts, ".Select(alert => new HudLayer.AlertLine", "RefreshAlerts must not allocate alert projection chains.", result);
        ForbidText(alerts, "_state.SelectedBuildings().Any()", "Command preview must not allocate legacy selected-building iterators.", result);
        ForbidText(alerts, ".Where(building => building.Owner == ProceduralRts.Core.Owner.Player && building.Hp > 0)", "Power alert must not allocate legacy building filter iterators.", result);
        ForbidText(alerts, ".Any(building => building.Kind == BuildingDesignIds.PowerPlant)", "Power alert must not allocate legacy building Any iterators.", result);
        ForbidText(alerts, "_state.Units.Count(unit =>", "Idle harvester alert must not allocate legacy unit count iterators.", result);
        ForbidText(alerts, ".ToList()", "RefreshAlerts must not allocate materialized alert lists.", result);
        ForbidText(sandbox, ".Where(unit => unit.PlayerSlotId == PlayerSlotId.One", "Sandbox launch selection must not allocate unit filter iterators.", result);
        ForbidText(sandbox, ".OrderBy(unit => unit.Position.DistanceSquaredTo", "Sandbox launch selection must sort reusable buffers in place.", result);
        ForbidText(sandbox, ".Select(unit => unit.Id)", "Sandbox launch selection must fill id storage explicitly.", result);
        ForbidText(sandbox, ".Select(building => building.Id)", "Sandbox structure next-id scans must not allocate building id projections.", result);
        ForbidText(sandbox, ".DefaultIfEmpty(0)", "Sandbox structure next-id scans must not allocate default LINQ chains.", result);
        ForbidText(hudState, "states.Take(12).ToArray()", "HudLayer command-card refresh must not allocate an ordered state array.", result);
        ForbidText(hudState, "orderedStates.Select(ProductionOptionId).ToHashSet()", "HudLayer command-card refresh must not allocate active id sets.", result);
        ForbidText(hudState, "_commandButtons.Keys.Where(key => !activeIds.Contains(key)).ToArray()", "HudLayer command-card refresh must not allocate stale key arrays.", result);

        var englishText = ReviewGateSource.Read(root, "scripts", "core", "localization", "GameText.English.cs");
        var chineseText = ReviewGateSource.Read(root, "scripts", "core", "localization", "GameText.ChineseSimplified.cs");
        RequireText(englishText, "[\"ui.detail.shieldField\"]", "English selected-unit ShieldField detail text must exist.", result);
        RequireText(englishText, "[\"ui.alert.insufficientCredits\"]", "English insufficient-credit HUD alert text must exist.", result);
        RequireText(englishText, "[\"production.batchQueued\"]", "English Shift production batch status text must exist.", result);
        RequireText(chineseText, "[\"ui.detail.shieldField\"]", "Chinese selected-unit ShieldField detail text must exist.", result);
        RequireText(chineseText, "[\"ui.alert.insufficientCredits\"]", "Chinese insufficient-credit HUD alert text must exist.", result);
        RequireText(chineseText, "[\"production.batchQueued\"]", "Chinese Shift production batch status text must exist.", result);
    }
}
