static class BattleRootHudAllocationReviewGate
{
    public static void Check(string root, GateResult result)
    {
        var battleRoot = ReviewGateEvidence.ReadSourceWithPartials(
            Path.Combine(root, "scripts", "BattleRoot.cs"));
        var process = ReviewGateSource.Read(root, "scripts", "BattleRoot.Process.cs");
        var minimap = ReviewGateSource.Read(root, "scripts", "battle-root", "BattleRoot.HudMinimap.cs");
        var alerts = ReviewGateSource.Read(root, "scripts", "BattleRoot.Alerts.cs");
        var sandbox = ReviewGateSource.Read(root, "scripts", "BattleRoot.Sandbox.cs");
        var hudState = ReviewGateSource.Read(root, "scripts", "ui", "hud", "HudLayer.State.cs");

        RequireText(battleRoot, "List<(Vector2 Position, float SightRange)> _unitBattlefieldVisionSourceBuffer", "BattleRoot vision source bridge must reuse storage.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapUnit> _minimapUnitBuffer", "BattleRoot minimap units must use reusable storage.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapUnit> _minimapUnitSecondaryBuffer", "BattleRoot minimap units must be double-buffered for redraw safety.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapBuilding> _minimapBuildingBuffer", "BattleRoot minimap buildings must use reusable storage.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapResource> _minimapResourceBuffer", "BattleRoot minimap resources must use reusable storage.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapAlertPing> _minimapAlertPingBuffer", "BattleRoot minimap alert pings must use reusable storage.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapAlertPing> _minimapAlertPingSecondaryBuffer", "BattleRoot minimap alert pings must be double-buffered for redraw safety.", result);
        RequireText(battleRoot, "List<HudLayer.AlertLine> _alertLineBuffer", "BattleRoot alert HUD sync must reuse alert line storage.", result);
        RequireText(battleRoot, "List<UnitInstance> _selectedUnitInstanceBuffer", "BattleRoot runtime selection HUD sync must reuse selected unit storage.", result);
        RequireText(battleRoot, "List<UnitModel> _selectedLegacyUnitBuffer", "BattleRoot legacy selection HUD sync must reuse selected unit storage.", result);
        RequireText(battleRoot, "List<BuildingModel> _selectedLegacyBuildingBuffer", "BattleRoot legacy selection HUD sync must reuse selected building storage.", result);
        RequireText(battleRoot, "List<int> _selectedProductionBuildingIdBuffer", "BattleRoot selected producer command-card sync must reuse selected building id storage.", result);
        RequireText(battleRoot, "SimEventSink _presentationEvents", "BattleRoot command acknowledgement feedback must use a SimEvent sink before drawing rings.", result);
        RequireText(battleRoot, "CommandAcknowledged = QueueCommandAcknowledgementEvent", "BattleRoot command acknowledgement callbacks must enqueue SimEvents instead of drawing rings directly.", result);
        RequireText(battleRoot, "_presentationEvents.Raise(new CommandAcknowledgedEvent", "BattleRoot command acknowledgement callbacks must raise CommandAcknowledgedEvent data.", result);
        RequireText(process, "DrainPresentationEvents();", "BattleRoot process must drain presentation SimEvents before drawing command acknowledgement rings.", result);
        RequireText(battleRoot, "_commandAcknowledgements.Add(acknowledgement.Kind, acknowledgement.Position)", "BattleRoot command acknowledgement rings must be applied from drained SimEvents.", result);
        RequireText(battleRoot, "PlayCommandAcknowledgementAudio(acknowledgement.AudioCue", "BattleRoot command audio cues must be applied from drained CommandAcknowledgedEvent data.", result);
        RequireText(ReviewGateSource.Read(root, "scripts", "controllers", "SelectionController.Commands.cs"), "AcknowledgeCommand(CommandAcknowledgementKind.Attack", "SelectionController command branches must send attack feedback through command acknowledgement events.", result);
        ForbidText(ReviewGateSource.Read(root, "scripts", "controllers", "SelectionController.Commands.cs"), "AudioCueRequested?.Invoke", "SelectionController command branches must not play command audio directly.", result);
        ForbidText(battleRoot, "CommandAcknowledged = AddCommandAcknowledgement", "BattleRoot command acknowledgement callbacks must not draw rings directly.", result);
        RequireText(battleRoot, "List<UnitInstance> _sandboxLaunchUnitBuffer", "BattleRoot sandbox launch selection must reuse unit storage.", result);
        RequireText(battleRoot, "List<int> _sandboxLaunchUnitIdBuffer", "BattleRoot sandbox launch selection must reuse id storage.", result);
        RequireText(battleRoot, "List<int> _debugPlayerAttackerIds", "Active battle perf setup must reuse player attacker id storage.", result);
        RequireText(battleRoot, "List<int> _debugEnemyAttackerIds", "Active battle perf setup must reuse enemy attacker id storage.", result);
        RequireText(process, "_unitBattlefieldVisionSourceBuffer.Clear();", "UnitBattlefieldVisionSources must clear and reuse the vision-source buffer.", result);
        RequireText(process, "foreach (var source in _unitBattlefield.VisionSources(PlayerSlotId.One))", "UnitBattlefieldVisionSources must copy vision sources explicitly.", result);
        RequireText(process, "_unitBattlefieldVisionSourceBuffer.Add((source.Position, source.SightRange));", "UnitBattlefieldVisionSources must fill the reusable vision-source buffer.", result);
        RequireText(process, "LiveUnitBattlefieldUnitCount()", "PerfHudCounts must use explicit runtime unit counting.", result);
        RequireText(process, "LiveLegacyUnitCount()", "PerfHudCounts must use explicit legacy unit counting.", result);
        RequireText(process, "LiveLegacyBuildingCount()", "PerfHudCounts must use explicit legacy building counting.", result);
        RequireText(process, "VisibleUnitViewCount()", "PerfHudCounts must use explicit visible unit view counting.", result);
        var hudSync = ReviewGateSource.Read(root, "scripts", "BattleRoot.HudSync.cs");
        var hudLayer = ReviewGateEvidence.ReadSourceWithPartials(Path.Combine(root, "scripts", "ui", "HudLayer.cs"));
        var hudBuild = ReviewGateSource.Read(root, "scripts", "ui", "hud", "HudLayer.Build.cs");
        var iconSummary = ReviewGateSource.Read(root, "scripts", "battle-root", "BattleRoot.SelectionIconSummary.cs");
        RequireText(hudBuild, "GameText.T(\"ui.tabs.command\")", "Production drawer tabs must expose the command build category.", result);
        RequireText(hudBuild, "GameText.T(\"ui.tabs.power\")", "Production drawer tabs must expose the power build category.", result);
        RequireText(hudBuild, "GameText.T(\"ui.tabs.economy\")", "Production drawer tabs must expose the economy build category.", result);
        RequireText(hudBuild, "GameText.T(\"ui.tabs.infantry\")", "Production drawer tabs must expose the infantry build category.", result);
        RequireText(hudBuild, "GameText.T(\"ui.tabs.vehicle\")", "Production drawer tabs must expose the vehicle build category.", result);
        RequireText(hudBuild, "GameText.T(\"ui.tabs.defense\")", "Production drawer tabs must expose the defense build category.", result);
        RequireText(hudBuild, "GameText.T(\"ui.tabs.air\")", "Production drawer tabs must expose the air build category.", result);
        RequireText(hudBuild, "GameText.T(\"ui.tabs.naval\")", "Production drawer tabs must expose the naval build category.", result);
        RequireText(hudBuild, "BuildCategory.Defense", "Production drawer tabs must carry typed build categories into HUD actions.", result);
        RequireText(hudLayer, "List<ProductionTab> _productionTabs", "Production drawer tabs must retain tab controls so selected state can update after clicks.", result);
        RequireText(hudLayer, "SelectProductionTab(category);", "Production drawer tabs must update the visible selected tab before routing build placement.", result);
        RequireText(hudLayer, "tab.SetSelected(tab.Category == category);", "Production drawer tabs must redraw selected state from the last requested build category.", result);
        RequireText(battleRoot, "BuildCategoryRequested = OnBuildCategoryRequested", "BattleRoot must wire build category tab requests into build placement.", result);
        RequireText(ReviewGateSource.Read(root, "scripts", "controllers", "BuildPlacementController.cs"), "public bool SelectBuildCategory(BuildCategory category)", "Build placement controller must expose a category selection entry point for HUD build tabs.", result);
        RequireText(hudBuild, "RibbonCancelProduction", "Command ribbon sell action must expose a stable node.", result);
        RequireText(hudLayer, "Action? SellOrCancelRequested", "HudLayer must expose the command-ribbon sell-or-cancel request.", result);
        RequireText(hudBuild, "ribbonCancel.Pressed += () => SellOrCancelRequested?.Invoke();", "Command ribbon sell action must route through the sell-or-cancel request path.", result);
        RequireText(hudBuild, "_cancelProduction.Pressed += () => CancelProductionRequested?.Invoke();", "Right-side queue cancel must stay on the production cancel request path.", result);
        RequireText(battleRoot, "SellOrCancelRequested = OnSellOrCancelRequested", "BattleRoot must wire the command-ribbon sell-or-cancel request.", result);
        RequireText(battleRoot, "_unitBattlefield.SellSelectedBuildings", "BattleRoot sell-or-cancel request must sell selected buildings before falling back to production cancel.", result);
        RequireText(ReviewGateSource.Read(root, "scripts", "core", "units", "runtime", "battlefield", "UnitBattlefield.BuildingSell.cs"), "BuildSpecCatalog.For(identity.Kind)", "Selected building sell must refund from the build spec instead of production cancel constants.", result);
        RequireText(ReviewGateSource.Read(root, "scripts", "core", "units", "runtime", "UnitBattlefieldBuildingDeathInfo.cs"), "UnitBattlefieldBuildingRemovalCause", "Runtime building removals must expose a removal cause.", result);
        RequireText(ReviewGateSource.Read(root, "scripts", "core", "units", "runtime", "UnitBattlefieldBuildingDeathInfo.cs"), "Sold", "Runtime building removals must distinguish sold structures from destroyed structures.", result);
        RequireText(hudLayer, "Action? RallyRequested", "HudLayer must expose the command-ribbon rally request.", result);
        RequireText(hudBuild, "RibbonSetRally", "Command ribbon rally action must expose a stable node.", result);
        RequireText(hudBuild, "ribbonRally.Pressed += () => RallyRequested?.Invoke();", "Command ribbon rally action must route through the rally request path.", result);
        RequireText(battleRoot, "RallyRequested = OnRallyRequested", "BattleRoot must wire the HUD rally request into selection commands.", result);
        RequireText(hudSync, "_selection.ArmRallyCommand();", "BattleRoot rally request must arm the SelectionController rally command mode.", result);
        RequireText(ReviewGateEvidence.ReadSourceWithPartials(Path.Combine(root, "scripts", "controllers", "SelectionController.cs")), "public void ArmRallyCommand()", "SelectionController must expose one-shot rally command arming for the command ribbon.", result);
        RequireText(ReviewGateEvidence.ReadSourceWithPartials(Path.Combine(root, "scripts", "controllers", "SelectionController.cs")), "FinishArmedRallyCommand(mouse.Position)", "Armed rally mode must finish through the selected-building rally backend on click.", result);
        RequireText(hudState, "Label _sandboxStateHashValue", "Sandbox developer HUD must own a state-hash readout label.", result);
        RequireText(hudBuild, "Name = \"SandboxStateHash\"", "Sandbox developer HUD must expose the state-hash readout as a stable node.", result);
        RequireText(sandbox, "SandboxDebugOverlayFlag.StateHash", "Sandbox state-hash readout must be gated by the debug overlay flag.", result);
        RequireText(sandbox, "_unitBattlefield.EntityWorld.DeterministicStateHash()", "Sandbox state-hash readout must use the live runtime EntityWorld hash.", result);
        RequireText(process, "RefreshSandboxStateHash();", "BattleRoot process must refresh sandbox state-hash overlay state.", result);
        RequireText(hudSync, "CollectSelectedProductionBuildingIds();", "Runtime command-card refresh must collect selected building ids once for command-card and queue sync.", result);
        RequireText(hudSync, "RuntimeProductionCommandCardStates(_selectedProductionBuildingIdBuffer)", "Runtime command-card refresh must route through selected-producer state selection.", result);
        RequireText(hudSync, "_unitBattlefield.ProductionDesignOptionStatesForSelectedProducers", "Runtime command-card refresh must use selected producer production options when available.", result);
        RequireText(hudSync, "RuntimeProductionQueueSummary(_selectedProductionBuildingIdBuffer, out var canCancel)", "Runtime queue summary refresh must route through selected-producer queue state selection.", result);
        RequireText(hudSync, "_unitBattlefield.ProductionQueueSummaryForSelectedProducers", "Runtime queue summary refresh must use selected producer queues when available.", result);
        RequireText(hudSync, "_unitBattlefield.CancelFirstProductionForSelectedProducers", "Runtime cancel button must cancel selected producer queues when available.", result);
        RequireText(hudSync, "if (hasSelectedProducers)", "Runtime producer HUD sync must fall back to aggregate state only when no selected producer exists.", result);
        RequireText(hudSync, "CollectSelectedUnitInstances(PlayerSlotId.One, _selectedUnitInstanceBuffer)", "Runtime selection HUD sync must fill the reusable selected-unit buffer.", result);
        RequireText(hudSync, "private void CollectSelectedUnitInstances(PlayerSlotId playerSlotId, List<UnitInstance> result)", "Runtime selection HUD sync must expose a reusable selected-unit collector.", result);
        RequireText(hudSync, "CollectSelectedLegacyUnits(_selectedLegacyUnitBuffer)", "Legacy selection HUD sync must fill the reusable selected-unit buffer.", result);
        RequireText(hudSync, "CollectSelectedLegacyBuildings(_selectedLegacyBuildingBuffer)", "Legacy selection HUD sync must fill the reusable selected-building buffer.", result);
        RequireText(hudSync, "foreach (var unit in units)", "Runtime selection HUD group stats must use explicit loops.", result);
        RequireText(hudSync, "foreach (var building in buildings)", "Runtime building selection HUD group stats must use explicit loops.", result);
        RequireText(hudSync, "foreach (var unit in selectedUnits)", "Legacy selection HUD unit stats must use explicit loops.", result);
        RequireText(hudSync, "foreach (var building in selectedBuildings)", "Legacy selection HUD building stats must use explicit loops.", result);
        RequireText(battleRoot, "for (var index = 1; index < selectedUnits.Count; index++)", "SelectedUniformStance must scan selected units without LINQ All.", result);
        RequireText(alerts, "HasSelectedLegacyBuildings()", "Command preview must use the explicit legacy building selection scan.", result);
        RequireText(alerts, "HasLegacyPlayerPowerPlant()", "Power alert must use the explicit legacy power-building scan.", result);
        RequireText(alerts, "IdleLegacyHarvesterCount()", "Idle harvester alert must use an explicit legacy harvester count scan.", result);
        RequireText(alerts, "private bool HasSelectedLegacyBuildings()", "BattleRoot alerts must expose the legacy selected-building scan helper.", result);
        RequireText(alerts, "private bool HasLegacyPlayerPowerPlant()", "BattleRoot alerts must expose the legacy power scan helper.", result);
        RequireText(alerts, "private int IdleLegacyHarvesterCount()", "BattleRoot alerts must expose the legacy idle harvester count scan helper.", result);
        RequireText(battleRoot, "CollectActiveBattlePerfAttackers(PlayerSlotId.One, _debugPlayerAttackerIds)", "Active battle perf setup must fill player attacker ids explicitly.", result);
        RequireText(battleRoot, "CollectActiveBattlePerfAttackers(PlayerSlotId.Two, _debugEnemyAttackerIds)", "Active battle perf setup must fill enemy attacker ids explicitly.", result);
        RequireText(battleRoot, "var designIds = new string[count];", "BattleRoot debug design-id readout must build an explicit stable snapshot.", result);
        RequireText(battleRoot, "designIds[index++] = unit.Spec.Id;", "BattleRoot debug design-id readout must fill snapshots with an explicit scan.", result);
        RequireText(sandbox, "CollectSandboxLaunchSelectionIds();", "Sandbox launch must fill reusable selected-unit id storage.", result);
        RequireText(sandbox, "_sandboxLaunchUnitBuffer.Sort(CompareSandboxLaunchUnits)", "Sandbox launch selection must sort reusable unit storage in place.", result);
        RequireText(sandbox, "NextSandboxBuildingTargetId()", "Sandbox structure spawn must compute next building id with an explicit scan.", result);
        RequireText(iconSummary, "List<SelectionIconSummaryEntry> _selectionIconSummaryEntries", "Selection icon summaries must reuse aggregation storage.", result);
        RequireText(iconSummary, "List<HudLayer.SelectionIconItem> _selectionIconSummarySecondaryBuffer", "Selection icon summaries must double-buffer HUD-owned item storage.", result);
        RequireText(iconSummary, "NextSelectionIconSummaryBuffer()", "Selection icon summaries must acquire reusable HUD item storage.", result);
        RequireText(iconSummary, "_useSecondarySelectionIconSummaryBuffer", "Selection icon summaries must alternate HUD item buffers.", result);
        RequireText(battleRoot, "FillMinimapUnits(units)", "RefreshMinimap must fill the reusable unit buffer.", result);
        RequireText(battleRoot, "FillUnitBattlefieldMinimapBuildings(buildings)", "RefreshMinimap must fill the reusable runtime building buffer.", result);
        RequireText(battleRoot, "FillMinimapResources(resources)", "RefreshMinimap must fill the reusable resource buffer.", result);
        RequireText(battleRoot, "FillMinimapAlertPings(alertPings)", "RefreshMinimap must fill active alert pings from reusable alert storage.", result);
        RequireText(minimap, "for (var index = 0; index < _alerts.Count; index++)", "BattleRoot minimap alert pings must scan active alerts explicitly.", result);
        RequireText(minimap, "alert.WorldPosition is not { } position", "BattleRoot minimap alert pings must come from world-positioned alerts.", result);
        RequireText(minimap, "result.Add(new HudLayer.MinimapAlertPing", "BattleRoot minimap alert pings must copy HUD presentation data explicitly.", result);
        RequireText(hudState, "IReadOnlyList<MinimapAlertPing>? alertPings = null", "HudLayer minimap state must accept active alert pings as optional presentation data.", result);
        RequireText(hudState, "_minimapSurface.AlertPings = alertPings ?? []", "HudLayer minimap state must keep alert ping assignment allocation-free.", result);
        RequireText(minimap, "foreach (var unit in _state.Units)", "BattleRoot minimap units must use an explicit scan.", result);
        RequireText(minimap, "foreach (var building in projections)", "BattleRoot runtime minimap buildings must copy projections explicitly.", result);
        RequireText(minimap, "foreach (var resource in pips)", "BattleRoot minimap resources must copy pips explicitly.", result);
        RequireText(hudState, "public readonly record struct MinimapAlertPing", "HudLayer must expose a compact minimap alert ping presentation record.", result);
        RequireText(alerts, "_alertLineBuffer.Clear();", "RefreshAlerts must clear and reuse the alert line buffer.", result);
        RequireText(alerts, "_alertLineBuffer.Count < 4", "RefreshAlerts must cap HUD alert lines without LINQ Take.", result);
        RequireText(alerts, "_hud.SetAlerts(_alertLineBuffer)", "RefreshAlerts must pass reusable alert lines to HudLayer.", result);
        RequireText(alerts, "private bool TryJumpToLatestPositionedAlert()", "BattleRoot alerts must expose a bounded latest-positioned-alert jump helper.", result);
        RequireText(alerts, "OnMinimapJumpRequested(worldPosition);", "Alert hotkey jump must reuse the existing minimap camera focus path.", result);
        RequireText(process, "key.Keycode == Key.Space && TryJumpToLatestPositionedAlert()", "BattleRoot input must route Space to the latest positioned alert before sandbox-only debug keys.", result);
        RequireText(hudState, "List<ProductionOptionState> _commandCardStates", "HudLayer command-card refresh must reuse visible state storage.", result);
        RequireText(hudState, "HashSet<string> _commandCardActiveIds", "HudLayer command-card refresh must reuse active id storage.", result);
        RequireText(hudState, "List<string> _commandCardStaleIds", "HudLayer command-card refresh must reuse stale id storage.", result);
        RequireText(hudState, "_commandCardStates.Add(state)", "HudLayer command-card refresh must fill reusable state storage.", result);
        RequireText(hudState, "_commandCardStaleIds.Add(key)", "HudLayer command-card refresh must collect stale keys before removing buttons.", result);
        ForbidText(minimap, ".ToList()", "BattleRoot minimap sync must not allocate materialized lists.", result);
        ForbidText(minimap, ".Select(", "BattleRoot minimap sync must not allocate LINQ projection chains.", result);
        ForbidText(minimap, ".Where(", "BattleRoot minimap sync must not allocate LINQ filter chains.", result);
        ForbidText(process, ".Select(source => (source.Position, source.SightRange))", "BattleRoot vision source bridge must not allocate LINQ projection iterators.", result);
        ForbidText(process, "_unitBattlefield.Units.Count(unit => unit.Hp > 0)", "PerfHudCounts must not allocate runtime live-unit count iterators.", result);
        ForbidText(process, "_state.Units.Count(unit => unit.Hp > 0)", "PerfHudCounts must not allocate legacy live-unit count iterators.", result);
        ForbidText(process, "_state.Buildings.Count(building => building.Hp > 0)", "PerfHudCounts must not allocate legacy live-building count iterators.", result);
        ForbidText(process, "_unitInstanceViews.Values.Count(view => view.Visible)", "PerfHudCounts must not allocate runtime visible-view count iterators.", result);
        ForbidText(process, "_unitViews.Values.Count(view => view.Visible)", "PerfHudCounts must not allocate legacy visible-view count iterators.", result);
        ForbidText(battleRoot, "_state.SelectedUnits().Count()", "BattleRoot selected-unit readouts must use explicit selected-unit count scans.", result);
        ForbidText(hudSync, "_unitBattlefield.SelectedUnits(PlayerSlotId.One).ToList()", "Runtime selection HUD sync must not materialize selected UnitBattlefield units.", result);
        ForbidText(hudSync, "_state.SelectedUnits().ToList()", "Legacy selection HUD sync must not materialize selected GameState units.", result);
        ForbidText(hudSync, "_state.SelectedBuildings().ToList()", "Legacy selection HUD sync must not materialize selected GameState buildings.", result);
        ForbidText(hudSync, "var combatUnits = units.Count(unit =>", "Runtime selection HUD group stats must not allocate LINQ count iterators.", result);
        ForbidText(hudSync, "var economyUnits = units.Count(unit =>", "Runtime selection HUD group stats must not allocate LINQ count iterators.", result);
        ForbidText(hudSync, "var cargo = units.Sum(unit => unit.Cargo)", "Runtime selection HUD group stats must not allocate LINQ sum iterators.", result);
        ForbidText(hudSync, "var avgHealth = units.Average(unit =>", "Runtime selection HUD group stats must not allocate LINQ average iterators.", result);
        ForbidText(hudSync, "buildings.Average(building =>", "Runtime building selection HUD group stats must not allocate LINQ average iterators.", result);
        ForbidText(hudSync, "selectedUnits.Count(unit =>", "Legacy selection HUD group stats must not allocate LINQ count iterators.", result);
        ForbidText(hudSync, "selectedUnits.Sum(unit => unit.Cargo)", "Legacy selection HUD group stats must not allocate LINQ sum iterators.", result);
        ForbidText(hudSync, "selectedUnits.Average(", "Legacy selection HUD group stats must not allocate LINQ average iterators.", result);
        ForbidText(hudSync, "selectedBuildings.Average(", "Legacy selection HUD group stats must not allocate LINQ average iterators.", result);
        ForbidText(battleRoot, ".All(unit => unit.Stance == stance)", "SelectedUniformStance must not allocate LINQ All iterators.", result);
        ForbidText(battleRoot, "var playerAttackers = _unitBattlefield.Units", "Active battle perf setup must not allocate player attacker LINQ chains.", result);
        ForbidText(battleRoot, "var enemyAttackers = _unitBattlefield.Units", "Active battle perf setup must not allocate enemy attacker LINQ chains.", result);
        ForbidText(battleRoot, ".Where(unit => unit.PlayerSlotId == PlayerSlotId.One && unit.Hp > 0 && unit.WeaponMounts.Count > 0)", "Active battle perf setup must scan player attackers explicitly.", result);
        ForbidText(battleRoot, ".Where(unit => unit.PlayerSlotId == PlayerSlotId.Two && unit.Hp > 0 && unit.WeaponMounts.Count > 0)", "Active battle perf setup must scan enemy attackers explicitly.", result);
        ForbidText(battleRoot, ".Select(unit => unit.Spec.Id)", "BattleRoot debug design-id readout must not allocate LINQ projection chains.", result);
        ForbidText(hudSync, ".GroupBy(", "Selection HUD sync must not allocate icon summary grouping chains.", result);
        ForbidText(hudSync, ".ToList()", "Selection HUD sync must not materialize icon summary lists.", result);
        ForbidText(iconSummary, ".GroupBy(", "Selection icon summaries must not allocate grouping chains.", result);
        ForbidText(iconSummary, ".OrderBy", "Selection icon summaries must sort reusable entries in place.", result);
        ForbidText(iconSummary, ".Select(", "Selection icon summaries must not allocate projection chains.", result);
        ForbidText(iconSummary, ".Distinct()", "Selection icon summaries must track faction uniformity explicitly.", result);
        ForbidText(iconSummary, ".ToList()", "Selection icon summaries must not allocate materialized lists.", result);
        ForbidText(alerts, ".OrderByDescending(alert => alert.CreatedAt)", "RefreshAlerts must not allocate ordered alert queries.", result);
        ForbidText(alerts, ".Take(4)", "RefreshAlerts must not allocate LINQ take queries.", result);
        ForbidText(alerts, ".Select(alert => new HudLayer.AlertLine", "RefreshAlerts must not allocate alert projection chains.", result);
        ForbidText(alerts, "_state.SelectedBuildings().Any()", "Command preview must not allocate legacy selected-building iterators.", result);
        ForbidText(alerts, ".Where(building => building.Owner == ProceduralRts.Core.Owner.Player && building.Hp > 0)", "Power alert must not allocate legacy building filter iterators.", result);
        ForbidText(alerts, ".Any(building => building.Kind == BuildingDesignIds.PowerPlant)", "Power alert must not allocate legacy building Any iterators.", result);
        ForbidText(alerts, "_state.Units.Count(unit =>", "Idle harvester alert must not allocate legacy unit count iterators.", result);
        ForbidText(alerts, ".ToList()", "RefreshAlerts must not allocate materialized alert lists.", result);
        ForbidText(sandbox, ".Where(unit => unit.PlayerSlotId == PlayerSlotId.One", "Sandbox launch selection must not allocate unit filter iterators.", result);
        ForbidText(sandbox, ".OrderBy(unit => unit.Position.DistanceSquaredTo", "Sandbox launch selection must sort reusable buffers in place.", result);
        ForbidText(sandbox, ".Select(unit => unit.Id)", "Sandbox launch selection must fill id storage explicitly.", result);
        ForbidText(sandbox, ".Select(building => building.Id)", "Sandbox structure next-id scans must not allocate building id projections.", result);
        ForbidText(sandbox, ".DefaultIfEmpty(0)", "Sandbox structure next-id scans must not allocate default LINQ chains.", result);
        ForbidText(hudState, "states.Take(12).ToArray()", "HudLayer command-card refresh must not allocate an ordered state array.", result);
        ForbidText(hudState, "orderedStates.Select(ProductionOptionId).ToHashSet()", "HudLayer command-card refresh must not allocate active id sets.", result);
        ForbidText(hudState, "_commandButtons.Keys.Where(key => !activeIds.Contains(key)).ToArray()", "HudLayer command-card refresh must not allocate stale key arrays.", result);
    }
}
