static class HoverTooltipReviewGate
{
    public static void Check(string root, GateResult result)
    {
        var preview = ReviewGateSource.Read(root, "scripts", "controllers", "SelectionController.Preview.cs");
        var tooltips = ReviewGateSource.Read(root, "scripts", "controllers", "SelectionController.HoverTooltips.cs");
        var hotkeys = ReviewGateSource.Read(root, "scripts", "ui", "HotkeyLegendLayer.cs");
        var controlBindingCatalog = ReviewGateSource.Read(root, "scripts", "core", "presentation", "ui", "ControlBindingCatalog.cs");
        var selectionInput = ReviewGateSource.Read(root, "scripts", "controllers", "SelectionController.cs");
        var rallyCommand = ReviewGateSource.Read(root, "scripts", "controllers", "SelectionController.RallyCommand.cs");
        var repairCommand = ReviewGateSource.Read(root, "scripts", "controllers", "SelectionController.RepairCommand.cs");
        var selectionHotkeys = ReviewGateSource.Read(root, "scripts", "controllers", "SelectionController.Hotkeys.cs");
        var previewKinds = ReviewGateSource.Read(root, "scripts", "core", "commands", "CommandPreviewKind.cs");
        var buildPlacement = ReviewGateEvidence.ReadSourceWithPartials(Path.Combine(root, "scripts", "controllers", "BuildPlacementController.cs"));
        var constructionTickets = ReviewGateSource.Read(root, "scripts", "core", "units", "runtime", "battlefield", "UnitBattlefield.ConstructionTickets.cs");
        var battleRootAlerts = ReviewGateSource.Read(root, "scripts", "BattleRoot.Alerts.cs");
        var hudPreview = ReviewGateSource.Read(root, "scripts", "ui", "hud", "HudLayer.CommandControls.cs");
        var hudLayer = ReviewGateEvidence.ReadSourceWithPartials(Path.Combine(root, "scripts", "ui", "HudLayer.cs"));
        var englishText = ReviewGateSource.Read(root, "scripts", "core", "localization", "GameText.English.cs");
        var chineseText = ReviewGateSource.Read(root, "scripts", "core", "localization", "GameText.ChineseSimplified.cs");

        RequireText(previewKinds, "Move,\n    Attack,\n    Repair,\n    Rally,\n    Harvest,\n    BuildValid,\n    BuildInvalid", "Command preview kinds must cover move/attack/repair/rally/harvest/build states.", result);
        RequireText(preview, "RuntimeUnitAttackPreviewLabel(hoveredUnitInstance.Spec)", "Runtime hostile unit hover must surface matchup text through the command preview.", result);
        RequireText(preview, "LegacyUnitAttackPreviewLabel(hoveredUnit)", "Legacy hostile unit hover must surface matchup text through the command preview.", result);
        RequireText(preview, "RuntimeBuildingAttackPreviewLabel(buildingProjection)", "Runtime hostile structure hover must surface matchup text through the command preview.", result);
        RequireText(preview, "LegacyBuildingAttackPreviewLabel(hoveredBuilding)", "Legacy hostile structure hover must surface matchup text through the command preview.", result);
        RequireText(preview, "CommandPreviewKind.Repair", "Selection preview must expose repair affordance state.", result);
        RequireText(preview, "RepairUnitPreviewLabel()", "Smart repair hover must label damaged friendly unit targets distinctly.", result);
        RequireText(preview, "RepairStructurePreviewLabel()", "Smart repair hover must label damaged friendly structure targets distinctly.", result);
        RequireText(repairCommand, "RepairInvalidPreviewLabel()", "Armed repair preview must label invalid repair targets distinctly.", result);
        RequireText(preview, "CommandPreviewKind.Harvest", "Selection preview must expose harvester resource state.", result);
        RequireText(preview, "CommandPreviewKind.Rally", "Selection preview must expose producer rally state.", result);
        RequireText(rallyCommand, "GameText.T(\"preview.rally.point\")", "Armed rally preview must label point targets distinctly.", result);
        RequireText(rallyCommand, "GameText.T(\"preview.rally.resource\")", "Armed rally preview must label resource targets distinctly.", result);
        RequireText(rallyCommand, "GameText.T(\"preview.rally.friendly\")", "Armed rally preview must label friendly-unit targets distinctly.", result);
        RequireText(preview, "CommandPreviewKind.Move", "Selection preview must expose move state.", result);
        RequireText(preview, "MoveModeStatus(PreviewMoveModeFromModifiers())", "Selection move preview must reuse command-mode labels instead of generic move text.", result);
        RequireText(preview, "Input.IsKeyPressed(Key.Ctrl)", "Selection move preview must expose Ctrl ignore-advance modifier feedback.", result);
        RequireText(preview, "Input.IsKeyPressed(Key.Alt)", "Selection move preview must expose Alt attack-advance modifier feedback.", result);
        RequireText(buildPlacement, "CommandPreviewKind.BuildValid", "Build placement preview must expose valid placement state.", result);
        RequireText(buildPlacement, "CommandPreviewKind.BuildInvalid", "Build placement preview must expose invalid placement state.", result);
        RequireText(buildPlacement, "DrawPlacementCursor(rect, accent, placementValid)", "Build placement must draw a distinct placement cursor.", result);
        RequireText(buildPlacement, "ReadyConstructionTickets(LocalPlayerSlotId)", "Build placement cycling must surface ready sidebar construction tickets.", result);
        RequireText(buildPlacement, "QueueConstructionTicket(LocalPlayerSlotId, kind", "Sidebar construction mode must queue a ticket before placement.", result);
        RequireText(buildPlacement, "PlaceReadyConstructionTicket(", "Build placement must place ready construction tickets through the runtime backend.", result);
        RequireText(buildPlacement, "CancelConstructionTicket(LocalPlayerSlotId, _activeReadyTicketId", "Build placement must cancel active ready construction tickets through the runtime backend.", result);
        RequireText(constructionTickets, "build.ticketCancelled", "Build placement must surface localized construction ticket refund feedback.", result);
        RequireText(buildPlacement, "DefaultMethodFor(LocalFaction)", "Build placement must choose deploy-vs-sidebar behavior from faction construction policy.", result);
        RequireText(buildPlacement, "HasEnoughCreditsForPreview(spec)", "Build placement preview must surface insufficient credits before commit.", result);
        RequireText(buildPlacement, "PlacementStatusLabel(\"placement.needCredits\"", "Build placement preview must reuse localized need-credit feedback.", result);
        RequireText(buildPlacement, "BuildingDesignIds.Headquarters,\n        BuildingDesignIds.GroundTurret,\n        BuildingDesignIds.Airfield,\n        BuildingDesignIds.AntiAirTurret", "Build placement cycle must expose defense and air structures represented by the HUD tabs.", result);
        RequireText(buildPlacement, "case Key.R when IsActive:", "Build placement must keep the active placement-rotation affordance.", result);
        RequireText(buildPlacement, "GameText.Format(\"build.rotated\", CurrentSpec().Label)", "Build placement rotation must surface localized status feedback.", result);
        RequireText(englishText, "[\"build.rotated\"]", "English build placement text must include rotation feedback.", result);
        RequireText(chineseText, "[\"build.rotated\"]", "Chinese build placement text must include rotation feedback.", result);
        RequireText(englishText, "[\"preview.rally.point\"] = \"RALLY POINT\"", "English rally point preview text must exist.", result);
        RequireText(englishText, "[\"preview.rally.resource\"] = \"RALLY RESOURCE\"", "English rally resource preview text must exist.", result);
        RequireText(englishText, "[\"preview.rally.friendly\"] = \"RALLY FOLLOW\"", "English rally friendly-unit preview text must exist.", result);
        RequireText(englishText, "[\"preview.repair.unit\"] = \"REPAIR UNIT\"", "English repair preview must distinguish unit repair targets.", result);
        RequireText(englishText, "[\"preview.repair.structure\"] = \"REPAIR STRUCTURE\"", "English repair preview must distinguish structure repair targets.", result);
        RequireText(englishText, "[\"preview.repair.invalid\"] = \"NO REPAIR TARGET\"", "English repair preview must label invalid repair targets.", result);
        RequireText(chineseText, "[\"preview.rally.point\"] = \"集结到地点\"", "Chinese rally point preview text must exist.", result);
        RequireText(chineseText, "[\"preview.rally.resource\"] = \"集结到资源\"", "Chinese rally resource preview text must exist.", result);
        RequireText(chineseText, "[\"preview.rally.friendly\"] = \"跟随友军集结\"", "Chinese rally friendly-unit preview text must exist.", result);
        RequireText(chineseText, "[\"preview.repair.unit\"] = \"修理单位\"", "Chinese repair preview must distinguish unit repair targets.", result);
        RequireText(chineseText, "[\"preview.repair.structure\"] = \"修理建筑\"", "Chinese repair preview must distinguish structure repair targets.", result);
        RequireText(chineseText, "[\"preview.repair.invalid\"] = \"无法修理\"", "Chinese repair preview must label invalid repair targets.", result);
        RequireText(battleRootAlerts, "_buildPlacement.IsActive ? _buildPlacement.PreviewState : _selection.PreviewState", "BattleRoot must route active build preview ahead of selection preview.", result);
        RequireText(tooltips, "MatchupFromScore(selectedArmed, targeters, bestScore)", "Hover matchup labels must be derived from selected-unit target coverage and combat profile score.", result);
        RequireText(tooltips, "preview.matchup.cannotTarget", "Hover matchup labels must expose cannot-target feedback.", result);
        RequireText(hotkeys, "_hint.Visible = false", "Closed hotkey legend must not leave persistent instructional HUD copy.", result);
        RequireText(hotkeys, "_hint.Visible = _open", "Hotkey legend hint may appear only while the transient legend panel is open.", result);
        RequireText(hotkeys, "_panel.SetAnchorsPreset(Control.LayoutPreset.TopRight)", "Hotkey legend panel must use a fixed top-right frame instead of viewport-height stretching.", result);
        RequireText(hotkeys, "private const float PanelHeight = 458f;", "Hotkey legend must keep a fixed 720p-safe panel height.", result);
        RequireText(hotkeys, "private const int LegendColumnCount = 2;", "Hotkey legend must use a compact two-column command reference.", result);
        RequireText(hotkeys, "var column = index % LegendColumnCount;", "Hotkey legend sections must flow into two columns instead of one tall stack.", result);
        RequireText(hotkeys, "ControlBindingCatalog.Sections", "Hotkey legend must draw rows from the shared binding catalog.", result);
        RequireText(controlBindingCatalog, "ControlBindingSectionKind.Catalog, \"hotkeys.catalog\"", "Shared binding catalog must include a right-catalog control section.", result);
        RequireText(hudLayer, "private void CycleCatalogMode(int direction)", "Right catalog pages must expose keyboard cycling through the same mode selection path.", result);
        RequireText(hudLayer, "key.Keycode == Key.Pageup", "Right catalog keyboard cycling must support PageUp.", result);
        RequireText(hudLayer, "key.Keycode == Key.Pagedown", "Right catalog keyboard cycling must support PageDown.", result);
        RequireText(englishText, "[\"hotkeys.catalog\"] = \"CATALOG\"", "English hotkey legend must label the right catalog section.", result);
        RequireText(englishText, "[\"hotkeys.catalog.1\"] = \"Tab right catalog drawer\"", "English hotkey legend must expose the right catalog drawer toggle.", result);
        RequireText(englishText, "[\"hotkeys.catalog.2\"] = \"PageUp/PageDown cycle pages\"", "English hotkey legend must expose right catalog page cycling.", result);
        RequireText(englishText, "[\"hotkeys.catalog.3\"] = \"Click cards / provider lanes\"", "English hotkey legend must expose right catalog card and provider interactions.", result);
        RequireText(englishText, "[\"hotkeys.orders.1\"] = \"Ribbon / RMB direct\"", "English hotkey legend must point move modes at visible ribbon controls and right-click modifiers.", result);
        RequireText(englishText, "[\"hotkeys.orders.2\"] = \"Ribbon / Alt+RMB attack\"", "English hotkey legend must point attack move at visible ribbon controls and right-click modifiers.", result);
        RequireText(englishText, "[\"hotkeys.orders.3\"] = \"Ribbon / Ctrl+RMB ignore\"", "English hotkey legend must point ignore move at visible ribbon controls and right-click modifiers.", result);
        RequireText(chineseText, "[\"hotkeys.orders.1\"] = \"命令栏 / 右键直接\"", "Chinese hotkey legend must point move modes at visible ribbon controls and right-click modifiers.", result);
        RequireText(chineseText, "[\"hotkeys.orders.2\"] = \"命令栏 / Alt+右键攻击\"", "Chinese hotkey legend must point attack move at visible ribbon controls and right-click modifiers.", result);
        RequireText(chineseText, "[\"hotkeys.orders.3\"] = \"命令栏 / Ctrl+右键无视\"", "Chinese hotkey legend must point ignore move at visible ribbon controls and right-click modifiers.", result);
        RequireText(chineseText, "[\"hotkeys.catalog\"] = \"目录\"", "Chinese hotkey legend must label the right catalog section.", result);
        RequireText(chineseText, "[\"hotkeys.catalog.1\"] = \"Tab 右侧目录抽屉\"", "Chinese hotkey legend must expose the right catalog drawer toggle.", result);
        RequireText(chineseText, "[\"hotkeys.catalog.2\"] = \"PageUp/PageDown 切换页面\"", "Chinese hotkey legend must expose right catalog page cycling.", result);
        RequireText(chineseText, "[\"hotkeys.catalog.3\"] = \"点击卡片/来源通道\"", "Chinese hotkey legend must expose right catalog card and provider interactions.", result);
        ForbidText(selectionInput, "HandleMoveModeHotkey", "Selection input must not dispatch a second move-mode hotkey path that conflicts with help/debug keys.", result);
        ForbidText(selectionHotkeys, "HandleMoveModeHotkey", "Selection hotkeys must not keep a dead move-mode hotkey handler.", result);
        ForbidText(selectionHotkeys, "Key.F1 => MoveCommandMode", "F1 must remain owned by the hotkey legend instead of also changing move mode.", result);
        ForbidText(selectionHotkeys, "Key.F2 => MoveCommandMode", "F2 must remain available to sandbox time-scale controls instead of also changing move mode.", result);
        ForbidText(selectionHotkeys, "Key.F3 => MoveCommandMode", "F3 must remain available to debug overlays instead of also changing move mode.", result);
        RequireText(hudPreview, "Preview.ScreenPosition + new Vector2(18, 18)", "Hover guidance must remain a transient cursor-side command preview instead of persistent HUD copy.", result);
        RequireText(hudPreview, "case CommandPreviewKind.Move:", "HUD command preview must render move as a distinct mode.", result);
        RequireText(hudPreview, "case CommandPreviewKind.Attack:", "HUD command preview must render attack as a distinct mode.", result);
        RequireText(hudPreview, "case CommandPreviewKind.Repair:", "HUD command preview must render repair as a distinct mode.", result);
        RequireText(hudPreview, "case CommandPreviewKind.Harvest:", "HUD command preview must render harvest as a distinct mode.", result);
        RequireText(hudPreview, "case CommandPreviewKind.Rally:", "HUD command preview must render rally as a distinct mode.", result);
        RequireText(hudPreview, "case CommandPreviewKind.BuildValid:", "HUD command preview must render build-valid as a distinct mode.", result);
        RequireText(hudPreview, "case CommandPreviewKind.BuildInvalid:", "HUD command preview must render build-invalid as a distinct mode.", result);
    }
}
