static class BattleRootHudAllocationReviewGate
{
    public static void Check(string root, GateResult result)
    {
        var battleRoot = ReviewGateEvidence.ReadSourceWithPartials(
            Path.Combine(root, "scripts", "BattleRoot.cs"));
        var process = ReviewGateSource.Read(root, "scripts", "BattleRoot.Process.cs");
        var minimap = ReviewGateSource.Read(root, "scripts", "battle-root", "BattleRoot.HudMinimap.cs");
        var alerts = ReviewGateSource.Read(root, "scripts", "BattleRoot.Alerts.cs");
        var hudState = ReviewGateSource.Read(root, "scripts", "ui", "hud", "HudLayer.State.cs");

        RequireText(battleRoot, "List<(Vector2 Position, float SightRange)> _unitBattlefieldVisionSourceBuffer", "BattleRoot vision source bridge must reuse storage.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapUnit> _minimapUnitBuffer", "BattleRoot minimap units must use reusable storage.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapUnit> _minimapUnitSecondaryBuffer", "BattleRoot minimap units must be double-buffered for redraw safety.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapBuilding> _minimapBuildingBuffer", "BattleRoot minimap buildings must use reusable storage.", result);
        RequireText(battleRoot, "List<HudLayer.MinimapResource> _minimapResourceBuffer", "BattleRoot minimap resources must use reusable storage.", result);
        RequireText(battleRoot, "List<HudLayer.AlertLine> _alertLineBuffer", "BattleRoot alert HUD sync must reuse alert line storage.", result);
        RequireText(battleRoot, "List<UnitInstance> _selectedUnitInstanceBuffer", "BattleRoot runtime selection HUD sync must reuse selected unit storage.", result);
        RequireText(battleRoot, "List<UnitModel> _selectedLegacyUnitBuffer", "BattleRoot legacy selection HUD sync must reuse selected unit storage.", result);
        RequireText(battleRoot, "List<BuildingModel> _selectedLegacyBuildingBuffer", "BattleRoot legacy selection HUD sync must reuse selected building storage.", result);
        RequireText(process, "_unitBattlefieldVisionSourceBuffer.Clear();", "UnitBattlefieldVisionSources must clear and reuse the vision-source buffer.", result);
        RequireText(process, "foreach (var source in _unitBattlefield.VisionSources(PlayerSlotId.One))", "UnitBattlefieldVisionSources must copy vision sources explicitly.", result);
        RequireText(process, "_unitBattlefieldVisionSourceBuffer.Add((source.Position, source.SightRange));", "UnitBattlefieldVisionSources must fill the reusable vision-source buffer.", result);
        RequireText(process, "LiveUnitBattlefieldUnitCount()", "PerfHudCounts must use explicit runtime unit counting.", result);
        RequireText(process, "LiveLegacyUnitCount()", "PerfHudCounts must use explicit legacy unit counting.", result);
        RequireText(process, "LiveLegacyBuildingCount()", "PerfHudCounts must use explicit legacy building counting.", result);
        RequireText(process, "VisibleUnitViewCount()", "PerfHudCounts must use explicit visible unit view counting.", result);
        var hudSync = ReviewGateSource.Read(root, "scripts", "BattleRoot.HudSync.cs");
        var iconSummary = ReviewGateSource.Read(root, "scripts", "battle-root", "BattleRoot.SelectionIconSummary.cs");
        RequireText(hudSync, "CollectSelectedUnitInstances(PlayerSlotId.One, _selectedUnitInstanceBuffer)", "Runtime selection HUD sync must fill the reusable selected-unit buffer.", result);
        RequireText(hudSync, "private void CollectSelectedUnitInstances(PlayerSlotId playerSlotId, List<UnitInstance> result)", "Runtime selection HUD sync must expose a reusable selected-unit collector.", result);
        RequireText(hudSync, "CollectSelectedLegacyUnits(_selectedLegacyUnitBuffer)", "Legacy selection HUD sync must fill the reusable selected-unit buffer.", result);
        RequireText(hudSync, "CollectSelectedLegacyBuildings(_selectedLegacyBuildingBuffer)", "Legacy selection HUD sync must fill the reusable selected-building buffer.", result);
        RequireText(hudSync, "foreach (var unit in units)", "Runtime selection HUD group stats must use explicit loops.", result);
        RequireText(hudSync, "foreach (var building in buildings)", "Runtime building selection HUD group stats must use explicit loops.", result);
        RequireText(hudSync, "foreach (var unit in selectedUnits)", "Legacy selection HUD unit stats must use explicit loops.", result);
        RequireText(hudSync, "foreach (var building in selectedBuildings)", "Legacy selection HUD building stats must use explicit loops.", result);
        RequireText(battleRoot, "for (var index = 1; index < selectedUnits.Count; index++)", "SelectedUniformStance must scan selected units without LINQ All.", result);
        RequireText(alerts, "HasSelectedLegacyBuildings()", "Command preview must use the explicit legacy building selection scan.", result);
        RequireText(alerts, "HasLegacyPlayerPowerPlant()", "Power alert must use the explicit legacy power-building scan.", result);
        RequireText(alerts, "IdleLegacyHarvesterCount()", "Idle harvester alert must use an explicit legacy harvester count scan.", result);
        RequireText(alerts, "private bool HasSelectedLegacyBuildings()", "BattleRoot alerts must expose the legacy selected-building scan helper.", result);
        RequireText(alerts, "private bool HasLegacyPlayerPowerPlant()", "BattleRoot alerts must expose the legacy power scan helper.", result);
        RequireText(alerts, "private int IdleLegacyHarvesterCount()", "BattleRoot alerts must expose the legacy idle harvester count scan helper.", result);
        RequireText(iconSummary, "List<SelectionIconSummaryEntry> _selectionIconSummaryEntries", "Selection icon summaries must reuse aggregation storage.", result);
        RequireText(iconSummary, "List<HudLayer.SelectionIconItem> _selectionIconSummarySecondaryBuffer", "Selection icon summaries must double-buffer HUD-owned item storage.", result);
        RequireText(iconSummary, "NextSelectionIconSummaryBuffer()", "Selection icon summaries must acquire reusable HUD item storage.", result);
        RequireText(iconSummary, "_useSecondarySelectionIconSummaryBuffer", "Selection icon summaries must alternate HUD item buffers.", result);
        RequireText(battleRoot, "FillMinimapUnits(units)", "RefreshMinimap must fill the reusable unit buffer.", result);
        RequireText(battleRoot, "FillUnitBattlefieldMinimapBuildings(buildings)", "RefreshMinimap must fill the reusable runtime building buffer.", result);
        RequireText(battleRoot, "FillMinimapResources(resources)", "RefreshMinimap must fill the reusable resource buffer.", result);
        RequireText(minimap, "foreach (var unit in _state.Units)", "BattleRoot minimap units must use an explicit scan.", result);
        RequireText(minimap, "foreach (var building in projections)", "BattleRoot runtime minimap buildings must copy projections explicitly.", result);
        RequireText(minimap, "foreach (var resource in pips)", "BattleRoot minimap resources must copy pips explicitly.", result);
        RequireText(alerts, "_alertLineBuffer.Clear();", "RefreshAlerts must clear and reuse the alert line buffer.", result);
        RequireText(alerts, "_alertLineBuffer.Count < 4", "RefreshAlerts must cap HUD alert lines without LINQ Take.", result);
        RequireText(alerts, "_hud.SetAlerts(_alertLineBuffer)", "RefreshAlerts must pass reusable alert lines to HudLayer.", result);
        RequireText(hudState, "List<ProductionOptionState> _commandCardStates", "HudLayer command-card refresh must reuse visible state storage.", result);
        RequireText(hudState, "HashSet<string> _commandCardActiveIds", "HudLayer command-card refresh must reuse active id storage.", result);
        RequireText(hudState, "List<string> _commandCardStaleIds", "HudLayer command-card refresh must reuse stale id storage.", result);
        RequireText(hudState, "_commandCardStates.Add(state)", "HudLayer command-card refresh must fill reusable state storage.", result);
        RequireText(hudState, "_commandCardStaleIds.Add(key)", "HudLayer command-card refresh must collect stale keys before removing buttons.", result);
        ForbidText(minimap, ".ToList()", "BattleRoot minimap sync must not allocate materialized lists.", result);
        ForbidText(minimap, ".Select(", "BattleRoot minimap sync must not allocate LINQ projection chains.", result);
        ForbidText(minimap, ".Where(", "BattleRoot minimap sync must not allocate LINQ filter chains.", result);
        ForbidText(process, ".Select(source => (source.Position, source.SightRange))", "BattleRoot vision source bridge must not allocate LINQ projection iterators.", result);
        ForbidText(process, "_unitBattlefield.Units.Count(unit => unit.Hp > 0)", "PerfHudCounts must not allocate runtime live-unit count iterators.", result);
        ForbidText(process, "_state.Units.Count(unit => unit.Hp > 0)", "PerfHudCounts must not allocate legacy live-unit count iterators.", result);
        ForbidText(process, "_state.Buildings.Count(building => building.Hp > 0)", "PerfHudCounts must not allocate legacy live-building count iterators.", result);
        ForbidText(process, "_unitInstanceViews.Values.Count(view => view.Visible)", "PerfHudCounts must not allocate runtime visible-view count iterators.", result);
        ForbidText(process, "_unitViews.Values.Count(view => view.Visible)", "PerfHudCounts must not allocate legacy visible-view count iterators.", result);
        ForbidText(battleRoot, "_state.SelectedUnits().Count()", "BattleRoot selected-unit readouts must use explicit selected-unit count scans.", result);
        ForbidText(hudSync, "_unitBattlefield.SelectedUnits(PlayerSlotId.One).ToList()", "Runtime selection HUD sync must not materialize selected UnitBattlefield units.", result);
        ForbidText(hudSync, "_state.SelectedUnits().ToList()", "Legacy selection HUD sync must not materialize selected GameState units.", result);
        ForbidText(hudSync, "_state.SelectedBuildings().ToList()", "Legacy selection HUD sync must not materialize selected GameState buildings.", result);
        ForbidText(hudSync, "var combatUnits = units.Count(unit =>", "Runtime selection HUD group stats must not allocate LINQ count iterators.", result);
        ForbidText(hudSync, "var economyUnits = units.Count(unit =>", "Runtime selection HUD group stats must not allocate LINQ count iterators.", result);
        ForbidText(hudSync, "var cargo = units.Sum(unit => unit.Cargo)", "Runtime selection HUD group stats must not allocate LINQ sum iterators.", result);
        ForbidText(hudSync, "var avgHealth = units.Average(unit =>", "Runtime selection HUD group stats must not allocate LINQ average iterators.", result);
        ForbidText(hudSync, "buildings.Average(building =>", "Runtime building selection HUD group stats must not allocate LINQ average iterators.", result);
        ForbidText(hudSync, "selectedUnits.Count(unit =>", "Legacy selection HUD group stats must not allocate LINQ count iterators.", result);
        ForbidText(hudSync, "selectedUnits.Sum(unit => unit.Cargo)", "Legacy selection HUD group stats must not allocate LINQ sum iterators.", result);
        ForbidText(hudSync, "selectedUnits.Average(", "Legacy selection HUD group stats must not allocate LINQ average iterators.", result);
        ForbidText(hudSync, "selectedBuildings.Average(", "Legacy selection HUD group stats must not allocate LINQ average iterators.", result);
        ForbidText(battleRoot, ".All(unit => unit.Stance == stance)", "SelectedUniformStance must not allocate LINQ All iterators.", result);
        ForbidText(hudSync, ".GroupBy(", "Selection HUD sync must not allocate icon summary grouping chains.", result);
        ForbidText(hudSync, ".ToList()", "Selection HUD sync must not materialize icon summary lists.", result);
        ForbidText(iconSummary, ".GroupBy(", "Selection icon summaries must not allocate grouping chains.", result);
        ForbidText(iconSummary, ".OrderBy", "Selection icon summaries must sort reusable entries in place.", result);
        ForbidText(iconSummary, ".Select(", "Selection icon summaries must not allocate projection chains.", result);
        ForbidText(iconSummary, ".Distinct()", "Selection icon summaries must track faction uniformity explicitly.", result);
        ForbidText(iconSummary, ".ToList()", "Selection icon summaries must not allocate materialized lists.", result);
        ForbidText(alerts, ".OrderByDescending(alert => alert.CreatedAt)", "RefreshAlerts must not allocate ordered alert queries.", result);
        ForbidText(alerts, ".Take(4)", "RefreshAlerts must not allocate LINQ take queries.", result);
        ForbidText(alerts, ".Select(alert => new HudLayer.AlertLine", "RefreshAlerts must not allocate alert projection chains.", result);
        ForbidText(alerts, "_state.SelectedBuildings().Any()", "Command preview must not allocate legacy selected-building iterators.", result);
        ForbidText(alerts, ".Where(building => building.Owner == ProceduralRts.Core.Owner.Player && building.Hp > 0)", "Power alert must not allocate legacy building filter iterators.", result);
        ForbidText(alerts, ".Any(building => building.Kind == BuildingDesignIds.PowerPlant)", "Power alert must not allocate legacy building Any iterators.", result);
        ForbidText(alerts, "_state.Units.Count(unit =>", "Idle harvester alert must not allocate legacy unit count iterators.", result);
        ForbidText(alerts, ".ToList()", "RefreshAlerts must not allocate materialized alert lists.", result);
        ForbidText(hudState, "states.Take(12).ToArray()", "HudLayer command-card refresh must not allocate an ordered state array.", result);
        ForbidText(hudState, "orderedStates.Select(ProductionOptionId).ToHashSet()", "HudLayer command-card refresh must not allocate active id sets.", result);
        ForbidText(hudState, "_commandButtons.Keys.Where(key => !activeIds.Contains(key)).ToArray()", "HudLayer command-card refresh must not allocate stale key arrays.", result);
    }
}
