static class GameStateAllocationReviewGate
{
    public static void Check(string root, GateResult result)
    {
        var gameState = ReviewGateSource.Read(root, "scripts", "core", "GameState.cs");
        RequireText(gameState, "List<PlacementBuildAnchor> _legacyPlacementBuildAnchors", "Legacy GameState placement validation must reuse build-anchor storage.", result);
        RequireText(gameState, "List<(ProductionKind Kind, UnitSpec Spec, ProductionSpec Production)> _legacyProductionSpecBuffer", "Legacy GameState production option states must reuse spec ordering storage.", result);
        RequireText(gameState, "List<UnitDeathInfo> _legacyUnitDeathBuffer", "Legacy GameState unit removal must reuse death event storage.", result);
        RequireText(gameState, "HashSet<int> _legacyRemovedUnitIds", "Legacy GameState unit removal must reuse removed-unit id storage.", result);
        RequireText(gameState, "List<int> _legacyRemovedBuildingIds", "Legacy GameState building removal must reuse removed-building event storage.", result);
        RequireText(gameState, "HashSet<int> _legacyRemovedBuildingIdSet", "Legacy GameState building removal must reuse removed-building lookup storage.", result);
        RequireText(gameState, "List<BuildingModel> _legacyRemovedBuildings", "Legacy GameState building removal must reuse outcome snapshot storage.", result);
        RequireText(gameState, "List<ProductionLaneSnapshot> _legacyProductionLaneSnapshotBuffer", "Legacy GameState production lane snapshots must reuse lane storage.", result);
        RequireText(gameState, "Dictionary<int, List<ProductionQueueSnapshot>> _legacyProductionQueueSnapshotBuffers", "Legacy GameState production queue snapshots must reuse per-producer storage.", result);
        RequireText(gameState, "List<BuildOptionSnapshot> _legacyBuildOptionSnapshotBuffer", "Legacy GameState build option snapshots must reuse result storage.", result);
        RequireText(gameState, "HashSet<string> _legacyReadyBuildingKinds", "Legacy GameState build option snapshots must reuse prerequisite lookup storage.", result);
        RequireText(gameState, "List<PlacementObstacle> _legacyPlacementObstacles", "Legacy GameState placement/path checks must reuse obstacle storage.", result);
        RequireText(gameState, "HashSet<GridObstacle> _legacyPathObstacleSet", "Legacy GameState path obstacles must reuse de-duplication storage.", result);
        RequireText(gameState, "Dictionary<GridObstacle, DynamicBlobObstacleBounds> _legacyDenseBlobObstacles", "Legacy GameState dense-blob path obstacles must reuse aggregation storage.", result);
        RequireText(gameState, "List<(Vector2 Position, float SightRange)> _legacyFogVisionSources", "Legacy GameState fog updates must reuse vision source storage.", result);
        RequireText(gameState, "List<LocalAvoidanceBody> _legacyLocalAvoidanceBodies", "Legacy GameState local avoidance must reuse body storage.", result);
        RequireText(gameState, "Dictionary<GridObstacle, List<LocalAvoidanceBody>> _legacyLocalAvoidanceHash", "Legacy GameState local avoidance must reuse hash bucket storage.", result);

        var economy = ReviewGateSource.Read(root, "scripts", "core", "game-state", "GameState.EconomyBuild.cs");
        RequireText(economy, "CollectProductionSpecsFor(MatchConfig.FactionForOwner(owner), _legacyProductionSpecBuffer)", "Legacy GameState production option states must fill reusable spec storage.", result);
        RequireText(economy, "ProductionOptionMetrics(owner, spec.Id, production)", "Legacy GameState production option states must scan producer metrics explicitly.", result);
        RequireText(economy, "result.Sort(CompareLegacyProductionSpecs)", "Legacy GameState production option specs must sort reusable storage in place.", result);
        RequireText(economy, "TryFindLeastQueuedProductionProducer(", "Legacy GameState production enqueue must scan for the least queued producer explicitly.", result);
        RequireText(economy, "TryFindFirstQueuedProductionProducer(owner)", "Legacy GameState production cancel must scan for the first queued producer explicitly.", result);
        RequireText(economy, "CollectBuildingBuildAnchors(owner, _legacyPlacementBuildAnchors)", "Legacy GameState placement validation must fill reusable build-anchor storage.", result);
        RequireText(economy, "CollectBuildingObstacles(_legacyPlacementObstacles)", "Legacy GameState placement validation must fill reusable obstacle storage.", result);
        ForbidText(economy, "ProductionSpecsFor(MatchConfig.FactionForOwner(owner))", "Legacy GameState production option states must not allocate production spec query chains.", result);
        ForbidText(economy, "var producers = Buildings", "Legacy GameState production option states must not materialize producer lists.", result);
        ForbidText(economy, "producers.Sum", "Legacy GameState production option metrics must not allocate LINQ Sum queries.", result);
        ForbidText(economy, ".DefaultIfEmpty(0)", "Legacy GameState production option progress must not allocate fallback query chains.", result);
        ForbidText(economy, "CandidateProductionProducers(owner, productionKind)", "Legacy GameState production enqueue must not allocate candidate producer iterators.", result);
        ForbidText(economy, ".OrderBy(option => option.Producer.ProductionQueue.Count)", "Legacy GameState production enqueue must not allocate producer ordering chains.", result);
        ForbidText(economy, ".ThenBy(option => option.Producer.Id)", "Legacy GameState production enqueue must not allocate producer id tie-break ordering chains.", result);
        ForbidText(economy, ".Where(building => building.Owner == owner)", "Legacy GameState production cancel must not allocate owner filter chains.", result);
        ForbidText(economy, ".OrderBy(building => building.ProductionQueue[0].Id)", "Legacy GameState production cancel must not allocate queue item ordering chains.", result);

        var productionSnapshots = ReviewGateSource.Read(root, "scripts", "core", "game-state", "GameState.ProductionSnapshots.cs");
        RequireText(productionSnapshots, "CollectProductionLaneSnapshots(owner, _legacyProductionLaneSnapshotBuffer)", "Legacy GameState production lane snapshots must fill reusable lane storage.", result);
        RequireText(productionSnapshots, "ProductionQueueSnapshotBufferFor(building.Id)", "Legacy GameState production lane snapshots must reuse per-producer queue storage.", result);
        RequireText(productionSnapshots, "CollectOwnedReadyBuildingKinds(owner, _legacyReadyBuildingKinds)", "Legacy GameState build option snapshots must fill reusable prerequisite storage.", result);
        RequireText(productionSnapshots, "result.Sort(CompareBuildOptionSnapshots)", "Legacy GameState build option snapshots must sort reusable storage in place.", result);
        ForbidText(productionSnapshots, ".OrderBy(building => building.Kind)", "Legacy GameState production lane snapshots must not allocate ordered building queries.", result);
        ForbidText(productionSnapshots, ".Select(item =>", "Legacy GameState production queue snapshots must not allocate item projection queries.", result);
        ForbidText(productionSnapshots, ".ToHashSet()", "Legacy GameState build option snapshots must not allocate prerequisite hashsets.", result);
        ForbidText(productionSnapshots, "RequiredBuildings.All", "Legacy GameState build option snapshots must scan prerequisites explicitly.", result);

        var picking = ReviewGateSource.Read(root, "scripts", "core", "game-state", "GameState.RelationsPickingFog.cs");
        RequireText(picking, "private void CollectBuildingBuildAnchors(Owner owner, List<PlacementBuildAnchor> result)", "Legacy GameState build-anchor collection must use caller-owned storage.", result);
        RequireText(picking, "CollectFogVisionSources(extraUnitSources, includeLegacyUnitSources, _legacyFogVisionSources)", "Legacy GameState fog updates must collect into reusable source storage.", result);
        RequireText(picking, "FogOfWar.Update(WorldSize, _legacyFogVisionSources)", "Legacy GameState fog updates must pass reusable source storage to FogOfWarMap.", result);
        RequireText(picking, "ResourceFieldModel? best = null", "Legacy GameState resource picking must use an explicit best-candidate scan.", result);
        RequireText(picking, "UnitModel? best = null", "Legacy GameState unit picking must use an explicit best-candidate scan.", result);
        RequireText(picking, "BuildingModel? best = null", "Legacy GameState building picking must use an explicit best-candidate scan.", result);
        RequireText(picking, "PickScore(distance, radius)", "Legacy GameState pick helpers must preserve normalized distance scoring.", result);
        ForbidText(picking, "private IReadOnlyList<PlacementBuildAnchor> BuildingBuildAnchors", "Legacy GameState build-anchor collection must not return allocating snapshots.", result);
        ForbidText(picking, "unitSources.Concat", "Legacy GameState fog updates must not allocate concatenated source enumerables.", result);
        ForbidText(picking, ".Select(unit => (unit.Position, unit.RuntimeDescriptor.SightRange))", "Legacy GameState fog updates must not allocate unit source projection queries.", result);
        ForbidText(picking, ".Select(building => (building.Position, BuildSpecCatalog.For(building.Kind).SightRange))", "Legacy GameState fog updates must not allocate building source projection queries.", result);
        ForbidText(picking, ".Where(candidate => candidate.Distance <= candidate.Radius)", "Legacy GameState pick helpers must not allocate candidate filter queries.", result);
        ForbidText(picking, ".OrderBy(candidate => candidate.Distance / Mathf.Max(candidate.Radius, 1))", "Legacy GameState pick helpers must not allocate ordered candidate queries.", result);
        ForbidText(picking, ".Select(candidate => candidate.", "Legacy GameState pick helpers must not allocate candidate projection queries.", result);

        var pathObstacles = ReviewGateSource.Read(root, "scripts", "core", "game-state", "GameState.PathObstacles.cs");
        RequireText(pathObstacles, "CollectPathPlacementObstacles(movingUnitId, movingUnitIds, _legacyPlacementObstacles)", "Legacy GameState path obstacles must fill reusable placement-obstacle storage.", result);
        RequireText(pathObstacles, "AppendGridCellsForObstacle(obstacle, PathCellSize, _legacyPathObstacles, _legacyPathObstacleSet)", "Legacy GameState path obstacles must append unique grid cells into reusable storage.", result);
        RequireText(pathObstacles, "_legacyDenseBlobObstacles.Clear()", "Legacy GameState dense-blob obstacles must reuse aggregation storage.", result);
        ForbidText(pathObstacles, ".Concat(BuildingObstacles())", "Legacy GameState path obstacles must not allocate concatenated obstacle enumerables.", result);
        ForbidText(pathObstacles, ".SelectMany(obstacle => GridCellsForObstacle", "Legacy GameState path obstacles must not allocate SelectMany grid-cell queries.", result);
        ForbidText(pathObstacles, ".GroupBy(unit => LocalAvoidanceMath.Cell", "Legacy GameState dense blob obstacles must not allocate grouping queries.", result);
        ForbidText(pathObstacles, "members.Min(unit =>", "Legacy GameState dense blob bounds must not allocate member lists/min queries.", result);
        var fogMap = ReviewGateSource.Read(root, "scripts", "core", "fog", "FogOfWarMap.cs");
        RequireText(fogMap, "visionSources as IReadOnlyList<(Vector2 Position, float SightRange)>", "FogOfWarMap.Update must not copy caller-owned source lists.", result);
        ForbidText(fogMap, "visionSources as (Vector2 Position, float SightRange)[] ?? visionSources.ToArray()", "FogOfWarMap.Update must not only recognize arrays as no-copy inputs.", result);
        ForbidText(fogMap, "sources.Length", "FogOfWarMap.Update must use IReadOnlyList.Count for source buffers.", result);

        var pathingAvoidance = ReviewGateSource.Read(root, "scripts", "core", "game-state", "GameState.PathingAvoidance.cs");
        RequireText(pathingAvoidance, "LocalAvoidanceMath.BuildHashInto(_legacyLocalAvoidanceBodies, LocalAvoidanceCellSize, _legacyLocalAvoidanceHash)", "Legacy GameState local avoidance must fill the reusable hash bucket dictionary.", result);
        ForbidText(pathingAvoidance, "LocalAvoidanceMath.BuildHash(", "Legacy GameState local avoidance must not use the allocating hash copy path.", result);
        ForbidText(pathingAvoidance, ".Where(unit => unit.Hp > 0)", "Legacy GameState local avoidance must not allocate alive-unit filter queries.", result);
        ForbidText(pathingAvoidance, ".Select(unit =>", "Legacy GameState local avoidance must not allocate body projection queries.", result);

        var targeting = ReviewGateSource.Read(root, "scripts", "core", "game-state", "GameState.TargetingThreat.cs");
        var targetScans = ReviewGateSource.Read(root, "scripts", "core", "game-state", "GameState.TargetScans.cs");
        var targetingSources = targeting + targetScans;
        RequireText(targeting, "BestUnitTargetForWeapon(building.Owner, weapon, building.Position, weapon.Range, requirePositiveHp: true)", "Legacy GameState building targeting must use the shared best-candidate scan.", result);
        RequireText(targeting, "BestUnitTargetForWeapon(unit.Owner, weapon, unit.Position, range, requirePositiveHp: false)", "Legacy GameState unit targeting must use the shared best-candidate scan.", result);
        RequireText(targetScans, "UnitModel? best = null", "Legacy GameState targeting scan must use explicit best-candidate storage.", result);
        RequireText(targetScans, "var score = TargetScore(weapon, sourcePosition, CombatTargetKind.Unit, candidate.Id, range)", "Legacy GameState targeting scan must preserve TargetScore selection.", result);
        ForbidText(targetingSources, ".Where(unit => IsTargetableHostile(building.Owner, unit)", "Legacy GameState building targeting must not allocate LINQ filter chains.", result);
        ForbidText(targetingSources, ".OrderByDescending(unit => TargetScore", "Legacy GameState building targeting must not allocate ordered target queries.", result);
        ForbidText(targetingSources, ".Where(candidate => IsTargetableHostile(unit.Owner, candidate))", "Legacy GameState unit targeting must not allocate LINQ filter chains.", result);
        ForbidText(targetingSources, ".OrderByDescending(candidate => TargetScore", "Legacy GameState unit targeting must not allocate ordered target queries.", result);

        var removal = ReviewGateSource.Read(root, "scripts", "core", "game-state", "GameState.RemovalDamageUtilities.cs");
        RequireText(removal, "_legacyUnitDeathBuffer.Add(new UnitDeathInfo", "Legacy GameState unit removal must fill reusable death storage.", result);
        RequireText(removal, "UnitsRemoved?.Invoke(_legacyUnitDeathBuffer)", "Legacy GameState unit removal must publish the reusable death buffer.", result);
        RequireText(removal, "BuildingsRemoved?.Invoke(_legacyRemovedBuildingIds)", "Legacy GameState building removal must publish the reusable id buffer.", result);
        RequireText(removal, "UpdateOutcomeAfterRemovedBuildings(_legacyRemovedBuildings)", "Legacy GameState building removal must reuse outcome snapshot storage.", result);
        ForbidText(removal, "Units.Where(unit => unit.Hp <= 0).ToList()", "Legacy GameState unit removal must not materialize removed-unit lists.", result);
        ForbidText(removal, "removedUnits.Select(unit => unit.Id).ToList()", "Legacy GameState unit removal must not materialize removed-unit id lists.", result);
        ForbidText(removal, "removedUnits\n            .Select(unit =>", "Legacy GameState unit removal must not materialize death projection lists.", result);
        ForbidText(removal, "Buildings.Where(building => building.Hp <= 0).Select(building => building.Id).ToList()", "Legacy GameState building removal must not materialize removed-building id lists.", result);
        ForbidText(removal, "Buildings.Where(building => removedIds.Contains(building.Id)).ToList()", "Legacy GameState building removal must not materialize removed-building snapshots.", result);
        ForbidText(removal, "removedBuildings.Any(", "Legacy GameState outcome checks must scan removed buildings explicitly.", result);

        var harvest = ReviewGateSource.Read(root, "scripts", "core", "game-state", "GameState.ProductionHarvest.cs");
        RequireText(harvest, "BuildingModel? best = null", "Legacy GameState refinery selection must use an explicit best-candidate scan.", result);
        RequireText(harvest, "var load = RefineryDockLoad(building, harvesterId)", "Legacy GameState refinery selection must preserve dock-load priority.", result);
        RequireText(harvest, "load < bestLoad || (load == bestLoad && distance < bestDistance)", "Legacy GameState refinery selection must preserve distance tie-breaks.", result);
        ForbidText(harvest, ".Where(building => building.Owner == owner)", "Legacy GameState refinery selection must not allocate owner filter chains.", result);
        ForbidText(harvest, ".OrderBy(building => RefineryDockLoad(building, harvesterId))", "Legacy GameState refinery selection must not allocate ordered refinery queries.", result);
        ForbidText(harvest, ".ThenBy(building => building.Position.DistanceTo(position))", "Legacy GameState refinery selection must not allocate secondary ordered refinery queries.", result);
        ForbidText(harvest, "Buildings.Where(building => building.Kind == BuildingDesignIds.Refinery)", "Legacy GameState dock cleanup must not allocate refinery filter chains.", result);

        var commands = ReviewGateSource.Read(root, "scripts", "core", "game-state", "GameState.Commands.cs");
        RequireText(gameState, "List<UnitModel> _legacySelectedHarvesters", "Legacy GameState harvest commands must reuse selected-harvester storage.", result);
        RequireText(gameState, "List<BuildingModel> _legacySelectedBuildings", "Legacy GameState rally commands must reuse selected-building storage.", result);
        RequireText(gameState, "List<BuildingModel> _legacySelectedProducers", "Legacy GameState rally commands must reuse selected-producer storage.", result);
        RequireText(gameState, "List<UnitModel> _legacySelectedCommandUnits", "Legacy GameState move/attack commands must reuse selected-unit storage.", result);
        RequireText(gameState, "Dictionary<int, FormationDestination> _legacyMoveDestinations", "Legacy move commands must reuse formation destination lookup storage.", result);
        RequireText(gameState, "Dictionary<int, PathfindingCorridorAssignment> _legacySharedMoveAssignments", "Legacy move commands must reuse shared-corridor assignment storage.", result);
        RequireText(gameState, "HashSet<int> _legacyMovingUnitIds", "Legacy move commands must reuse moving-unit id storage.", result);
        RequireText(gameState, "List<PathfindingCorridorMember> _legacyPathCorridorMembers", "Legacy move commands must reuse corridor member storage.", result);
        RequireText(gameState, "List<(Vector2 Position, float Radius)> _legacyAttackOccupiedSlots", "Legacy attack commands must reuse occupied-slot storage.", result);
        RequireText(gameState, "Dictionary<int, Vector2> _legacyAttackSlots", "Legacy attack commands must reuse attack-slot storage.", result);
        RequireText(commands, "CollectSelectedHarvesters(_legacySelectedHarvesters)", "Legacy harvest command must fill reusable harvester storage.", result);
        RequireText(commands, "CollectSelectedBuildings(_legacySelectedBuildings)", "Legacy rally command must fill reusable selected-building storage.", result);
        RequireText(commands, "CollectSelectedProductionBuildings(_legacySelectedBuildings, _legacySelectedProducers)", "Legacy rally command must fill reusable producer storage.", result);
        RequireText(commands, "CollectSelectedCommandUnits(_legacySelectedCommandUnits)", "Legacy move command must fill reusable selected-unit storage.", result);
        RequireText(commands, "PrepareLegacyMoveCommandBuffers(_legacySelectedCommandUnits, target)", "Legacy move command must prepare reusable formation and corridor buffers.", result);
        RequireText(commands, "CollectSelectedAttackCommandUnits(targetKind, targetId, _legacySelectedCommandUnits)", "Legacy attack command must fill reusable selected-attacker storage.", result);
        var commandBuffers = ReviewGateSource.Read(root, "scripts", "core", "game-state", "GameState.CommandBuffers.cs");
        RequireText(commandBuffers, "FormationMath.CreateMoveDestinationsInto(", "Legacy move command must use caller-owned formation buffers.", result);
        RequireText(commandBuffers, "CollectLegacyMoveDomainAssignments(selected, target, MovementDomain.Land", "Legacy move command must scan movement domains without GroupBy.", result);
        RequireText(commandBuffers, "CollectOccupiedAttackSlots(targetKind, targetId, excludedUnitId: 0, _legacyAttackOccupiedSlots)", "Legacy attack command must reuse occupied-slot storage.", result);
        RequireText(commandBuffers, "private UnitModel? NextAttackSlotUnit", "Legacy attack slot ordering must use an explicit best-candidate scan.", result);
        RequireText(commandBuffers, "private void CollectOccupiedAttackSlots(", "Manual attack refresh must share the reusable occupied-slot collector.", result);
        var movement = ReviewGateSource.Read(root, "scripts", "core", "game-state", "GameState.Movement.cs");
        RequireText(movement, "CollectOccupiedAttackSlots(", "Manual attack refresh must fill reusable occupied-slot storage.", result);
        ForbidText(commands, "SelectedUnits()\n            .Where(IsHarvesterUnit)\n            .ToList()", "Legacy harvest command must not materialize selected harvester lists.", result);
        ForbidText(commands, "SelectedBuildings().ToList()", "Legacy rally command must not materialize selected building lists.", result);
        ForbidText(commands, ".Where(IsProductionBuilding)\n            .ToList()", "Legacy rally command must not materialize selected producer lists.", result);
        ForbidText(commands, "SelectedUnits().ToList()", "Legacy move command must not materialize selected unit lists.", result);
        ForbidText(commands, ".Select(unit => new FormationUnit", "Legacy move command must not allocate formation projection chains.", result);
        ForbidText(commands, ".ToDictionary(destination => destination.Id)", "Legacy move command must not allocate destination dictionaries per command.", result);
        ForbidText(commandBuffers, ".GroupBy(unit => unit.RuntimeDescriptor.MovementDomain)", "Legacy move command must not allocate movement-domain groupings.", result);
        ForbidText(commandBuffers, ".ToHashSet()", "Legacy move command must not allocate moving-id hash sets.", result);
        ForbidText(commands, ".Where(unit => IsCombatTargetHostile(unit.Owner, targetKind, targetId))", "Legacy attack command must not allocate selected attacker filter chains.", result);
        ForbidText(commandBuffers, ".OrderBy(unit => unit.Position.DistanceTo(targetPosition))", "Legacy attack slot ordering must not allocate ordered LINQ chains.", result);
        ForbidText(commandBuffers, "units.Where(unit => IsUnitAtEngagementRange", "Legacy attack slots must not allocate in-range attacker filters.", result);
        ForbidText(commandBuffers, "Units\n            .Where(unit => unit.Hp > 0 && unit.MovementState == UnitMovementState.CombatAnchor)", "Legacy attack slots must not allocate occupied-slot queries.", result);
        ForbidText(movement, "Units\n            .Where(other => other.Id != unit.Id && other.Hp > 0 && other.MovementState == UnitMovementState.CombatAnchor)", "Manual attack refresh must not allocate occupied-slot queries.", result);

        var selection = ReviewGateSource.Read(root, "scripts", "core", "game-state", "GameState.Selection.cs");
        RequireText(gameState, "List<int> _legacySelectedUnitIds", "Legacy selection id snapshots must reuse id storage.", result);
        RequireText(gameState, "HashSet<int> _legacyRequestedSelectionIds", "Legacy id recall must reuse requested-id storage.", result);
        RequireText(gameState, "List<UnitModel> _legacySelectionRectHarvesters", "Legacy rect selection must reuse harvester storage.", result);
        RequireText(gameState, "List<UnitModel> _legacySelectionRectCombatUnits", "Legacy rect selection must reuse combat-unit storage.", result);
        RequireText(selection, "_legacySelectedUnitIds.Clear()", "Legacy SelectedUnitIds must fill reusable id storage.", result);
        RequireText(selection, "_legacyRequestedSelectionIds.Clear()", "Legacy SelectUnitsByIds must reuse requested-id storage.", result);
        RequireText(selection, "CollectSelectionRectUnits(normalizedRect, _legacySelectionRectHarvesters, _legacySelectionRectCombatUnits)", "Legacy rect selection must fill reusable unit-class buffers.", result);
        RequireText(selection, "NearestSelectionDistance(harvestersInRect, center)", "Legacy rect selection must compute nearest harvester explicitly.", result);
        ForbidText(selection, "SelectedUnits().Count()", "Legacy selection methods must not allocate selected-unit Count queries.", result);
        ForbidText(selection, "SelectedBuildings().Count()", "Legacy selection methods must not allocate selected-building Count queries.", result);
        ForbidText(selection, "SelectedUnits().Select(unit => unit.Id).ToList()", "Legacy SelectedUnitIds must not materialize LINQ id lists.", result);
        ForbidText(selection, "unitIds.ToHashSet()", "Legacy SelectUnitsByIds must not allocate requested-id HashSets.", result);
        ForbidText(selection, "var unitsInRect = Units\n            .Where", "Legacy rect selection must not materialize units-in-rect lists.", result);
        ForbidText(selection, "harvestersInRect.Min(unit =>", "Legacy rect selection must not allocate nearest-harvester Min queries.", result);
        ForbidText(selection, "combatUnitsInRect.Min(unit =>", "Legacy rect selection must not allocate nearest-combat Min queries.", result);
    }
}
